// Code generated by protoc-gen-go. DO NOT EDIT.
// source: open.proto

package open

import (
	context "context"
	fmt "fmt"
	api "github.com/Kotodian/protocol/golang/api"
	common "github.com/Kotodian/protocol/golang/common"
	coregw "github.com/Kotodian/protocol/golang/coregw"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MerchantApplyStatus int32

const (
	MerchantApplyStatus_MerchantApplyStatusUnknown   MerchantApplyStatus = 0
	MerchantApplyStatus_MerchantApplyStatusPending   MerchantApplyStatus = 10
	MerchantApplyStatus_MerchantApplyStatusProcess   MerchantApplyStatus = 20
	MerchantApplyStatus_MerchantApplyStatusProcessed MerchantApplyStatus = 30
	MerchantApplyStatus_MerchantApplyStatusClose     MerchantApplyStatus = 40
)

var MerchantApplyStatus_name = map[int32]string{
	0:  "MerchantApplyStatusUnknown",
	10: "MerchantApplyStatusPending",
	20: "MerchantApplyStatusProcess",
	30: "MerchantApplyStatusProcessed",
	40: "MerchantApplyStatusClose",
}

var MerchantApplyStatus_value = map[string]int32{
	"MerchantApplyStatusUnknown":   0,
	"MerchantApplyStatusPending":   10,
	"MerchantApplyStatusProcess":   20,
	"MerchantApplyStatusProcessed": 30,
	"MerchantApplyStatusClose":     40,
}

func (x MerchantApplyStatus) String() string {
	return proto.EnumName(MerchantApplyStatus_name, int32(x))
}

func (MerchantApplyStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{0}
}

type ApplyResourceType int32

const (
	ApplyResourceType_ApplyResourceTypeUnknow       ApplyResourceType = 0
	ApplyResourceType_ApplyResourceTypeCommercial   ApplyResourceType = 1
	ApplyResourceType_ApplyResourceTypeManufacturer ApplyResourceType = 2
	ApplyResourceType_ApplyResourceTypeOperator     ApplyResourceType = 3
	ApplyResourceType_ApplyResourceTypeHardware     ApplyResourceType = 4
	ApplyResourceType_ApplyResourceTypeGoverment    ApplyResourceType = 5
	ApplyResourceType_ApplyResourceTypeProperty     ApplyResourceType = 6
	ApplyResourceType_ApplyResourceTypePersonal     ApplyResourceType = 7
)

var ApplyResourceType_name = map[int32]string{
	0: "ApplyResourceTypeUnknow",
	1: "ApplyResourceTypeCommercial",
	2: "ApplyResourceTypeManufacturer",
	3: "ApplyResourceTypeOperator",
	4: "ApplyResourceTypeHardware",
	5: "ApplyResourceTypeGoverment",
	6: "ApplyResourceTypeProperty",
	7: "ApplyResourceTypePersonal",
}

var ApplyResourceType_value = map[string]int32{
	"ApplyResourceTypeUnknow":       0,
	"ApplyResourceTypeCommercial":   1,
	"ApplyResourceTypeManufacturer": 2,
	"ApplyResourceTypeOperator":     3,
	"ApplyResourceTypeHardware":     4,
	"ApplyResourceTypeGoverment":    5,
	"ApplyResourceTypeProperty":     6,
	"ApplyResourceTypePersonal":     7,
}

func (x ApplyResourceType) String() string {
	return proto.EnumName(ApplyResourceType_name, int32(x))
}

func (ApplyResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{1}
}

type WithdrawStatus int32

const (
	WithdrawStatus_WithdrawStatus_InProcess WithdrawStatus = 0
	WithdrawStatus_WithdrawStatus_Fail      WithdrawStatus = -10
	WithdrawStatus_WithdrawStatus_Success   WithdrawStatus = 10
)

var WithdrawStatus_name = map[int32]string{
	0:   "WithdrawStatus_InProcess",
	-10: "WithdrawStatus_Fail",
	10:  "WithdrawStatus_Success",
}

var WithdrawStatus_value = map[string]int32{
	"WithdrawStatus_InProcess": 0,
	"WithdrawStatus_Fail":      -10,
	"WithdrawStatus_Success":   10,
}

func (x WithdrawStatus) String() string {
	return proto.EnumName(WithdrawStatus_name, int32(x))
}

func (WithdrawStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{2}
}

type MerchantInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantInfoReq) Reset()         { *m = MerchantInfoReq{} }
func (m *MerchantInfoReq) String() string { return proto.CompactTextString(m) }
func (*MerchantInfoReq) ProtoMessage()    {}
func (*MerchantInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{0}
}

func (m *MerchantInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantInfoReq.Unmarshal(m, b)
}
func (m *MerchantInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantInfoReq.Marshal(b, m, deterministic)
}
func (m *MerchantInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantInfoReq.Merge(m, src)
}
func (m *MerchantInfoReq) XXX_Size() int {
	return xxx_messageInfo_MerchantInfoReq.Size(m)
}
func (m *MerchantInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantInfoReq proto.InternalMessageInfo

type MerchantInfoResp struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	ImgUrl               string   `protobuf:"bytes,5,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	Balance              float64  `protobuf:"fixed64,6,opt,name=balance,proto3" json:"balance,omitempty"`
	CustomerId           uint64   `protobuf:"varint,7,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty,string"`
	BankAccount          string   `protobuf:"bytes,8,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	BankAccountName      string   `protobuf:"bytes,9,opt,name=bank_account_name,json=bankAccountName,proto3" json:"bank_account_name,omitempty"`
	BankCode             string   `protobuf:"bytes,10,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	BankName             string   `protobuf:"bytes,11,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantInfoResp) Reset()         { *m = MerchantInfoResp{} }
func (m *MerchantInfoResp) String() string { return proto.CompactTextString(m) }
func (*MerchantInfoResp) ProtoMessage()    {}
func (*MerchantInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{1}
}

func (m *MerchantInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantInfoResp.Unmarshal(m, b)
}
func (m *MerchantInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantInfoResp.Marshal(b, m, deterministic)
}
func (m *MerchantInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantInfoResp.Merge(m, src)
}
func (m *MerchantInfoResp) XXX_Size() int {
	return xxx_messageInfo_MerchantInfoResp.Size(m)
}
func (m *MerchantInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantInfoResp proto.InternalMessageInfo

func (m *MerchantInfoResp) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MerchantInfoResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerchantInfoResp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *MerchantInfoResp) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *MerchantInfoResp) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *MerchantInfoResp) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *MerchantInfoResp) GetCustomerId() uint64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *MerchantInfoResp) GetBankAccount() string {
	if m != nil {
		return m.BankAccount
	}
	return ""
}

func (m *MerchantInfoResp) GetBankAccountName() string {
	if m != nil {
		return m.BankAccountName
	}
	return ""
}

func (m *MerchantInfoResp) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *MerchantInfoResp) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

type BindBankCardReq struct {
	BankAccount          string   `protobuf:"bytes,1,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	BankAccountName      string   `protobuf:"bytes,2,opt,name=bank_account_name,json=bankAccountName,proto3" json:"bank_account_name,omitempty"`
	BankCode             string   `protobuf:"bytes,3,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindBankCardReq) Reset()         { *m = BindBankCardReq{} }
func (m *BindBankCardReq) String() string { return proto.CompactTextString(m) }
func (*BindBankCardReq) ProtoMessage()    {}
func (*BindBankCardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{2}
}

func (m *BindBankCardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindBankCardReq.Unmarshal(m, b)
}
func (m *BindBankCardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindBankCardReq.Marshal(b, m, deterministic)
}
func (m *BindBankCardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindBankCardReq.Merge(m, src)
}
func (m *BindBankCardReq) XXX_Size() int {
	return xxx_messageInfo_BindBankCardReq.Size(m)
}
func (m *BindBankCardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BindBankCardReq.DiscardUnknown(m)
}

var xxx_messageInfo_BindBankCardReq proto.InternalMessageInfo

func (m *BindBankCardReq) GetBankAccount() string {
	if m != nil {
		return m.BankAccount
	}
	return ""
}

func (m *BindBankCardReq) GetBankAccountName() string {
	if m != nil {
		return m.BankAccountName
	}
	return ""
}

func (m *BindBankCardReq) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

type BindBankCardResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindBankCardResp) Reset()         { *m = BindBankCardResp{} }
func (m *BindBankCardResp) String() string { return proto.CompactTextString(m) }
func (*BindBankCardResp) ProtoMessage()    {}
func (*BindBankCardResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{3}
}

func (m *BindBankCardResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindBankCardResp.Unmarshal(m, b)
}
func (m *BindBankCardResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindBankCardResp.Marshal(b, m, deterministic)
}
func (m *BindBankCardResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindBankCardResp.Merge(m, src)
}
func (m *BindBankCardResp) XXX_Size() int {
	return xxx_messageInfo_BindBankCardResp.Size(m)
}
func (m *BindBankCardResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BindBankCardResp.DiscardUnknown(m)
}

var xxx_messageInfo_BindBankCardResp proto.InternalMessageInfo

type UnbindBankCardReq struct {
	BankAccount          string   `protobuf:"bytes,1,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbindBankCardReq) Reset()         { *m = UnbindBankCardReq{} }
func (m *UnbindBankCardReq) String() string { return proto.CompactTextString(m) }
func (*UnbindBankCardReq) ProtoMessage()    {}
func (*UnbindBankCardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{4}
}

func (m *UnbindBankCardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindBankCardReq.Unmarshal(m, b)
}
func (m *UnbindBankCardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindBankCardReq.Marshal(b, m, deterministic)
}
func (m *UnbindBankCardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindBankCardReq.Merge(m, src)
}
func (m *UnbindBankCardReq) XXX_Size() int {
	return xxx_messageInfo_UnbindBankCardReq.Size(m)
}
func (m *UnbindBankCardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindBankCardReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindBankCardReq proto.InternalMessageInfo

func (m *UnbindBankCardReq) GetBankAccount() string {
	if m != nil {
		return m.BankAccount
	}
	return ""
}

type UnbindBankCardResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbindBankCardResp) Reset()         { *m = UnbindBankCardResp{} }
func (m *UnbindBankCardResp) String() string { return proto.CompactTextString(m) }
func (*UnbindBankCardResp) ProtoMessage()    {}
func (*UnbindBankCardResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{5}
}

func (m *UnbindBankCardResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindBankCardResp.Unmarshal(m, b)
}
func (m *UnbindBankCardResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindBankCardResp.Marshal(b, m, deterministic)
}
func (m *UnbindBankCardResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindBankCardResp.Merge(m, src)
}
func (m *UnbindBankCardResp) XXX_Size() int {
	return xxx_messageInfo_UnbindBankCardResp.Size(m)
}
func (m *UnbindBankCardResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindBankCardResp.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindBankCardResp proto.InternalMessageInfo

type MerchantApplyReq struct {
	UserName             string             `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	EvseNum              int32              `protobuf:"varint,2,opt,name=evse_num,json=evseNum,proto3" json:"evse_num,omitempty"`
	VehicleType          coregw.VehicleType `protobuf:"varint,3,opt,name=vehicle_type,json=vehicleType,proto3,enum=coregw.VehicleType" json:"vehicle_type,omitempty"`
	ResourceType         ApplyResourceType  `protobuf:"varint,4,opt,name=resource_type,json=resourceType,proto3,enum=open.ApplyResourceType" json:"resource_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MerchantApplyReq) Reset()         { *m = MerchantApplyReq{} }
func (m *MerchantApplyReq) String() string { return proto.CompactTextString(m) }
func (*MerchantApplyReq) ProtoMessage()    {}
func (*MerchantApplyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{6}
}

func (m *MerchantApplyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantApplyReq.Unmarshal(m, b)
}
func (m *MerchantApplyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantApplyReq.Marshal(b, m, deterministic)
}
func (m *MerchantApplyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantApplyReq.Merge(m, src)
}
func (m *MerchantApplyReq) XXX_Size() int {
	return xxx_messageInfo_MerchantApplyReq.Size(m)
}
func (m *MerchantApplyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantApplyReq.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantApplyReq proto.InternalMessageInfo

func (m *MerchantApplyReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *MerchantApplyReq) GetEvseNum() int32 {
	if m != nil {
		return m.EvseNum
	}
	return 0
}

func (m *MerchantApplyReq) GetVehicleType() coregw.VehicleType {
	if m != nil {
		return m.VehicleType
	}
	return coregw.VehicleType_Unknown
}

func (m *MerchantApplyReq) GetResourceType() ApplyResourceType {
	if m != nil {
		return m.ResourceType
	}
	return ApplyResourceType_ApplyResourceTypeUnknow
}

type MerchantApplyResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantApplyResp) Reset()         { *m = MerchantApplyResp{} }
func (m *MerchantApplyResp) String() string { return proto.CompactTextString(m) }
func (*MerchantApplyResp) ProtoMessage()    {}
func (*MerchantApplyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{7}
}

func (m *MerchantApplyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantApplyResp.Unmarshal(m, b)
}
func (m *MerchantApplyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantApplyResp.Marshal(b, m, deterministic)
}
func (m *MerchantApplyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantApplyResp.Merge(m, src)
}
func (m *MerchantApplyResp) XXX_Size() int {
	return xxx_messageInfo_MerchantApplyResp.Size(m)
}
func (m *MerchantApplyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantApplyResp.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantApplyResp proto.InternalMessageInfo

type MerchantApplyInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantApplyInfoReq) Reset()         { *m = MerchantApplyInfoReq{} }
func (m *MerchantApplyInfoReq) String() string { return proto.CompactTextString(m) }
func (*MerchantApplyInfoReq) ProtoMessage()    {}
func (*MerchantApplyInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{8}
}

func (m *MerchantApplyInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantApplyInfoReq.Unmarshal(m, b)
}
func (m *MerchantApplyInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantApplyInfoReq.Marshal(b, m, deterministic)
}
func (m *MerchantApplyInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantApplyInfoReq.Merge(m, src)
}
func (m *MerchantApplyInfoReq) XXX_Size() int {
	return xxx_messageInfo_MerchantApplyInfoReq.Size(m)
}
func (m *MerchantApplyInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantApplyInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantApplyInfoReq proto.InternalMessageInfo

type MerchantApplyInfoResp struct {
	UserName             string              `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	EvseNum              int32               `protobuf:"varint,2,opt,name=evse_num,json=evseNum,proto3" json:"evse_num,omitempty"`
	VehicleType          coregw.VehicleType  `protobuf:"varint,3,opt,name=vehicle_type,json=vehicleType,proto3,enum=coregw.VehicleType" json:"vehicle_type,omitempty"`
	ResourceType         ApplyResourceType   `protobuf:"varint,4,opt,name=resource_type,json=resourceType,proto3,enum=open.ApplyResourceType" json:"resource_type,omitempty"`
	Status               MerchantApplyStatus `protobuf:"varint,5,opt,name=status,proto3,enum=open.MerchantApplyStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MerchantApplyInfoResp) Reset()         { *m = MerchantApplyInfoResp{} }
func (m *MerchantApplyInfoResp) String() string { return proto.CompactTextString(m) }
func (*MerchantApplyInfoResp) ProtoMessage()    {}
func (*MerchantApplyInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{9}
}

func (m *MerchantApplyInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantApplyInfoResp.Unmarshal(m, b)
}
func (m *MerchantApplyInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantApplyInfoResp.Marshal(b, m, deterministic)
}
func (m *MerchantApplyInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantApplyInfoResp.Merge(m, src)
}
func (m *MerchantApplyInfoResp) XXX_Size() int {
	return xxx_messageInfo_MerchantApplyInfoResp.Size(m)
}
func (m *MerchantApplyInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantApplyInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantApplyInfoResp proto.InternalMessageInfo

func (m *MerchantApplyInfoResp) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *MerchantApplyInfoResp) GetEvseNum() int32 {
	if m != nil {
		return m.EvseNum
	}
	return 0
}

func (m *MerchantApplyInfoResp) GetVehicleType() coregw.VehicleType {
	if m != nil {
		return m.VehicleType
	}
	return coregw.VehicleType_Unknown
}

func (m *MerchantApplyInfoResp) GetResourceType() ApplyResourceType {
	if m != nil {
		return m.ResourceType
	}
	return ApplyResourceType_ApplyResourceTypeUnknow
}

func (m *MerchantApplyInfoResp) GetStatus() MerchantApplyStatus {
	if m != nil {
		return m.Status
	}
	return MerchantApplyStatus_MerchantApplyStatusUnknown
}

type MerchantStationsReq struct {
	Pagereq              *common.PageReq `protobuf:"bytes,1,opt,name=pagereq,proto3" json:"pagereq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MerchantStationsReq) Reset()         { *m = MerchantStationsReq{} }
func (m *MerchantStationsReq) String() string { return proto.CompactTextString(m) }
func (*MerchantStationsReq) ProtoMessage()    {}
func (*MerchantStationsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{10}
}

func (m *MerchantStationsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantStationsReq.Unmarshal(m, b)
}
func (m *MerchantStationsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantStationsReq.Marshal(b, m, deterministic)
}
func (m *MerchantStationsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantStationsReq.Merge(m, src)
}
func (m *MerchantStationsReq) XXX_Size() int {
	return xxx_messageInfo_MerchantStationsReq.Size(m)
}
func (m *MerchantStationsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantStationsReq.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantStationsReq proto.InternalMessageInfo

func (m *MerchantStationsReq) GetPagereq() *common.PageReq {
	if m != nil {
		return m.Pagereq
	}
	return nil
}

type MerchantStationsResp struct {
	Pageresp             *common.PageResp `protobuf:"bytes,1,opt,name=pageresp,proto3" json:"pageresp,omitempty"`
	Stations             []*api.Station   `protobuf:"bytes,2,rep,name=stations,proto3" json:"stations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MerchantStationsResp) Reset()         { *m = MerchantStationsResp{} }
func (m *MerchantStationsResp) String() string { return proto.CompactTextString(m) }
func (*MerchantStationsResp) ProtoMessage()    {}
func (*MerchantStationsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{11}
}

func (m *MerchantStationsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantStationsResp.Unmarshal(m, b)
}
func (m *MerchantStationsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantStationsResp.Marshal(b, m, deterministic)
}
func (m *MerchantStationsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantStationsResp.Merge(m, src)
}
func (m *MerchantStationsResp) XXX_Size() int {
	return xxx_messageInfo_MerchantStationsResp.Size(m)
}
func (m *MerchantStationsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantStationsResp.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantStationsResp proto.InternalMessageInfo

func (m *MerchantStationsResp) GetPageresp() *common.PageResp {
	if m != nil {
		return m.Pageresp
	}
	return nil
}

func (m *MerchantStationsResp) GetStations() []*api.Station {
	if m != nil {
		return m.Stations
	}
	return nil
}

type EvsesByStationReq struct {
	Pagereq              *common.PageReq `protobuf:"bytes,1,opt,name=pagereq,proto3" json:"pagereq,omitempty"`
	StationId            uint64          `protobuf:"varint,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty,string"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EvsesByStationReq) Reset()         { *m = EvsesByStationReq{} }
func (m *EvsesByStationReq) String() string { return proto.CompactTextString(m) }
func (*EvsesByStationReq) ProtoMessage()    {}
func (*EvsesByStationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{12}
}

func (m *EvsesByStationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvsesByStationReq.Unmarshal(m, b)
}
func (m *EvsesByStationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvsesByStationReq.Marshal(b, m, deterministic)
}
func (m *EvsesByStationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvsesByStationReq.Merge(m, src)
}
func (m *EvsesByStationReq) XXX_Size() int {
	return xxx_messageInfo_EvsesByStationReq.Size(m)
}
func (m *EvsesByStationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EvsesByStationReq.DiscardUnknown(m)
}

var xxx_messageInfo_EvsesByStationReq proto.InternalMessageInfo

func (m *EvsesByStationReq) GetPagereq() *common.PageReq {
	if m != nil {
		return m.Pagereq
	}
	return nil
}

func (m *EvsesByStationReq) GetStationId() uint64 {
	if m != nil {
		return m.StationId
	}
	return 0
}

type EvsesByStationResp struct {
	Pageresp             *common.PageResp `protobuf:"bytes,1,opt,name=pageresp,proto3" json:"pageresp,omitempty"`
	Evses                []*coregw.Evse   `protobuf:"bytes,2,rep,name=Evses,proto3" json:"Evses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EvsesByStationResp) Reset()         { *m = EvsesByStationResp{} }
func (m *EvsesByStationResp) String() string { return proto.CompactTextString(m) }
func (*EvsesByStationResp) ProtoMessage()    {}
func (*EvsesByStationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{13}
}

func (m *EvsesByStationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvsesByStationResp.Unmarshal(m, b)
}
func (m *EvsesByStationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvsesByStationResp.Marshal(b, m, deterministic)
}
func (m *EvsesByStationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvsesByStationResp.Merge(m, src)
}
func (m *EvsesByStationResp) XXX_Size() int {
	return xxx_messageInfo_EvsesByStationResp.Size(m)
}
func (m *EvsesByStationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EvsesByStationResp.DiscardUnknown(m)
}

var xxx_messageInfo_EvsesByStationResp proto.InternalMessageInfo

func (m *EvsesByStationResp) GetPageresp() *common.PageResp {
	if m != nil {
		return m.Pageresp
	}
	return nil
}

func (m *EvsesByStationResp) GetEvses() []*coregw.Evse {
	if m != nil {
		return m.Evses
	}
	return nil
}

type SetStationOperationStatusReq struct {
	StationId            uint64   `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty,string"`
	IsInOperation        bool     `protobuf:"varint,2,opt,name=is_in_operation,json=isInOperation,proto3" json:"is_in_operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStationOperationStatusReq) Reset()         { *m = SetStationOperationStatusReq{} }
func (m *SetStationOperationStatusReq) String() string { return proto.CompactTextString(m) }
func (*SetStationOperationStatusReq) ProtoMessage()    {}
func (*SetStationOperationStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{14}
}

func (m *SetStationOperationStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStationOperationStatusReq.Unmarshal(m, b)
}
func (m *SetStationOperationStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStationOperationStatusReq.Marshal(b, m, deterministic)
}
func (m *SetStationOperationStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStationOperationStatusReq.Merge(m, src)
}
func (m *SetStationOperationStatusReq) XXX_Size() int {
	return xxx_messageInfo_SetStationOperationStatusReq.Size(m)
}
func (m *SetStationOperationStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStationOperationStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetStationOperationStatusReq proto.InternalMessageInfo

func (m *SetStationOperationStatusReq) GetStationId() uint64 {
	if m != nil {
		return m.StationId
	}
	return 0
}

func (m *SetStationOperationStatusReq) GetIsInOperation() bool {
	if m != nil {
		return m.IsInOperation
	}
	return false
}

type SetStationOperationStatusResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStationOperationStatusResp) Reset()         { *m = SetStationOperationStatusResp{} }
func (m *SetStationOperationStatusResp) String() string { return proto.CompactTextString(m) }
func (*SetStationOperationStatusResp) ProtoMessage()    {}
func (*SetStationOperationStatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{15}
}

func (m *SetStationOperationStatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStationOperationStatusResp.Unmarshal(m, b)
}
func (m *SetStationOperationStatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStationOperationStatusResp.Marshal(b, m, deterministic)
}
func (m *SetStationOperationStatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStationOperationStatusResp.Merge(m, src)
}
func (m *SetStationOperationStatusResp) XXX_Size() int {
	return xxx_messageInfo_SetStationOperationStatusResp.Size(m)
}
func (m *SetStationOperationStatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStationOperationStatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetStationOperationStatusResp proto.InternalMessageInfo

type StationBindEvseReq struct {
	StationId            uint64   `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty,string"`
	QrcodePath           string   `protobuf:"bytes,2,opt,name=qrcode_path,json=qrcodePath,proto3" json:"qrcode_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StationBindEvseReq) Reset()         { *m = StationBindEvseReq{} }
func (m *StationBindEvseReq) String() string { return proto.CompactTextString(m) }
func (*StationBindEvseReq) ProtoMessage()    {}
func (*StationBindEvseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{16}
}

func (m *StationBindEvseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StationBindEvseReq.Unmarshal(m, b)
}
func (m *StationBindEvseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StationBindEvseReq.Marshal(b, m, deterministic)
}
func (m *StationBindEvseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StationBindEvseReq.Merge(m, src)
}
func (m *StationBindEvseReq) XXX_Size() int {
	return xxx_messageInfo_StationBindEvseReq.Size(m)
}
func (m *StationBindEvseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StationBindEvseReq.DiscardUnknown(m)
}

var xxx_messageInfo_StationBindEvseReq proto.InternalMessageInfo

func (m *StationBindEvseReq) GetStationId() uint64 {
	if m != nil {
		return m.StationId
	}
	return 0
}

func (m *StationBindEvseReq) GetQrcodePath() string {
	if m != nil {
		return m.QrcodePath
	}
	return ""
}

type StationBindEvseResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StationBindEvseResp) Reset()         { *m = StationBindEvseResp{} }
func (m *StationBindEvseResp) String() string { return proto.CompactTextString(m) }
func (*StationBindEvseResp) ProtoMessage()    {}
func (*StationBindEvseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{17}
}

func (m *StationBindEvseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StationBindEvseResp.Unmarshal(m, b)
}
func (m *StationBindEvseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StationBindEvseResp.Marshal(b, m, deterministic)
}
func (m *StationBindEvseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StationBindEvseResp.Merge(m, src)
}
func (m *StationBindEvseResp) XXX_Size() int {
	return xxx_messageInfo_StationBindEvseResp.Size(m)
}
func (m *StationBindEvseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StationBindEvseResp.DiscardUnknown(m)
}

var xxx_messageInfo_StationBindEvseResp proto.InternalMessageInfo

type StationUnbindEvseReq struct {
	StationId            uint64   `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty,string"`
	EvseId               uint64   `protobuf:"varint,2,opt,name=evse_id,json=evseId,proto3" json:"evse_id,omitempty,string"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StationUnbindEvseReq) Reset()         { *m = StationUnbindEvseReq{} }
func (m *StationUnbindEvseReq) String() string { return proto.CompactTextString(m) }
func (*StationUnbindEvseReq) ProtoMessage()    {}
func (*StationUnbindEvseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{18}
}

func (m *StationUnbindEvseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StationUnbindEvseReq.Unmarshal(m, b)
}
func (m *StationUnbindEvseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StationUnbindEvseReq.Marshal(b, m, deterministic)
}
func (m *StationUnbindEvseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StationUnbindEvseReq.Merge(m, src)
}
func (m *StationUnbindEvseReq) XXX_Size() int {
	return xxx_messageInfo_StationUnbindEvseReq.Size(m)
}
func (m *StationUnbindEvseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StationUnbindEvseReq.DiscardUnknown(m)
}

var xxx_messageInfo_StationUnbindEvseReq proto.InternalMessageInfo

func (m *StationUnbindEvseReq) GetStationId() uint64 {
	if m != nil {
		return m.StationId
	}
	return 0
}

func (m *StationUnbindEvseReq) GetEvseId() uint64 {
	if m != nil {
		return m.EvseId
	}
	return 0
}

type StationUnbindEvseResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StationUnbindEvseResp) Reset()         { *m = StationUnbindEvseResp{} }
func (m *StationUnbindEvseResp) String() string { return proto.CompactTextString(m) }
func (*StationUnbindEvseResp) ProtoMessage()    {}
func (*StationUnbindEvseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{19}
}

func (m *StationUnbindEvseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StationUnbindEvseResp.Unmarshal(m, b)
}
func (m *StationUnbindEvseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StationUnbindEvseResp.Marshal(b, m, deterministic)
}
func (m *StationUnbindEvseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StationUnbindEvseResp.Merge(m, src)
}
func (m *StationUnbindEvseResp) XXX_Size() int {
	return xxx_messageInfo_StationUnbindEvseResp.Size(m)
}
func (m *StationUnbindEvseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StationUnbindEvseResp.DiscardUnknown(m)
}

var xxx_messageInfo_StationUnbindEvseResp proto.InternalMessageInfo

type WithdrawApplyReq struct {
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawApplyReq) Reset()         { *m = WithdrawApplyReq{} }
func (m *WithdrawApplyReq) String() string { return proto.CompactTextString(m) }
func (*WithdrawApplyReq) ProtoMessage()    {}
func (*WithdrawApplyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{20}
}

func (m *WithdrawApplyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawApplyReq.Unmarshal(m, b)
}
func (m *WithdrawApplyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawApplyReq.Marshal(b, m, deterministic)
}
func (m *WithdrawApplyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawApplyReq.Merge(m, src)
}
func (m *WithdrawApplyReq) XXX_Size() int {
	return xxx_messageInfo_WithdrawApplyReq.Size(m)
}
func (m *WithdrawApplyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawApplyReq.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawApplyReq proto.InternalMessageInfo

func (m *WithdrawApplyReq) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type WithdrawApplyResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawApplyResp) Reset()         { *m = WithdrawApplyResp{} }
func (m *WithdrawApplyResp) String() string { return proto.CompactTextString(m) }
func (*WithdrawApplyResp) ProtoMessage()    {}
func (*WithdrawApplyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{21}
}

func (m *WithdrawApplyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawApplyResp.Unmarshal(m, b)
}
func (m *WithdrawApplyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawApplyResp.Marshal(b, m, deterministic)
}
func (m *WithdrawApplyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawApplyResp.Merge(m, src)
}
func (m *WithdrawApplyResp) XXX_Size() int {
	return xxx_messageInfo_WithdrawApplyResp.Size(m)
}
func (m *WithdrawApplyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawApplyResp.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawApplyResp proto.InternalMessageInfo

type Withdraw struct {
	Id                   uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`
	ManagerId            uint64         `protobuf:"varint,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty,string"`
	BankAccount          string         `protobuf:"bytes,3,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	BankAccountName      string         `protobuf:"bytes,4,opt,name=bank_account_name,json=bankAccountName,proto3" json:"bank_account_name,omitempty"`
	BankCode             string         `protobuf:"bytes,5,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	BankName             string         `protobuf:"bytes,6,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	Amount               float64        `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee                  float64        `protobuf:"fixed64,8,opt,name=fee,proto3" json:"fee,omitempty"`
	Status               WithdrawStatus `protobuf:"varint,9,opt,name=status,proto3,enum=open.WithdrawStatus" json:"status,omitempty"`
	Reason               string         `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`
	OpManagerId          uint64         `protobuf:"varint,11,opt,name=op_manager_id,json=opManagerId,proto3" json:"op_manager_id,omitempty,string"`
	CreatedAt            uint64         `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty,string"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Withdraw) Reset()         { *m = Withdraw{} }
func (m *Withdraw) String() string { return proto.CompactTextString(m) }
func (*Withdraw) ProtoMessage()    {}
func (*Withdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{22}
}

func (m *Withdraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Withdraw.Unmarshal(m, b)
}
func (m *Withdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Withdraw.Marshal(b, m, deterministic)
}
func (m *Withdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Withdraw.Merge(m, src)
}
func (m *Withdraw) XXX_Size() int {
	return xxx_messageInfo_Withdraw.Size(m)
}
func (m *Withdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_Withdraw.DiscardUnknown(m)
}

var xxx_messageInfo_Withdraw proto.InternalMessageInfo

func (m *Withdraw) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Withdraw) GetManagerId() uint64 {
	if m != nil {
		return m.ManagerId
	}
	return 0
}

func (m *Withdraw) GetBankAccount() string {
	if m != nil {
		return m.BankAccount
	}
	return ""
}

func (m *Withdraw) GetBankAccountName() string {
	if m != nil {
		return m.BankAccountName
	}
	return ""
}

func (m *Withdraw) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *Withdraw) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *Withdraw) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Withdraw) GetFee() float64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Withdraw) GetStatus() WithdrawStatus {
	if m != nil {
		return m.Status
	}
	return WithdrawStatus_WithdrawStatus_InProcess
}

func (m *Withdraw) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Withdraw) GetOpManagerId() uint64 {
	if m != nil {
		return m.OpManagerId
	}
	return 0
}

func (m *Withdraw) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type WithdrawRecordReq struct {
	Pagereq              *common.PageReq `protobuf:"bytes,1,opt,name=pagereq,proto3" json:"pagereq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WithdrawRecordReq) Reset()         { *m = WithdrawRecordReq{} }
func (m *WithdrawRecordReq) String() string { return proto.CompactTextString(m) }
func (*WithdrawRecordReq) ProtoMessage()    {}
func (*WithdrawRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{23}
}

func (m *WithdrawRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRecordReq.Unmarshal(m, b)
}
func (m *WithdrawRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRecordReq.Marshal(b, m, deterministic)
}
func (m *WithdrawRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRecordReq.Merge(m, src)
}
func (m *WithdrawRecordReq) XXX_Size() int {
	return xxx_messageInfo_WithdrawRecordReq.Size(m)
}
func (m *WithdrawRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRecordReq proto.InternalMessageInfo

func (m *WithdrawRecordReq) GetPagereq() *common.PageReq {
	if m != nil {
		return m.Pagereq
	}
	return nil
}

type WithdrawRecordResp struct {
	Pageresp             *common.PageResp `protobuf:"bytes,1,opt,name=pageresp,proto3" json:"pageresp,omitempty"`
	Withdraws            []*Withdraw      `protobuf:"bytes,2,rep,name=withdraws,proto3" json:"withdraws,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WithdrawRecordResp) Reset()         { *m = WithdrawRecordResp{} }
func (m *WithdrawRecordResp) String() string { return proto.CompactTextString(m) }
func (*WithdrawRecordResp) ProtoMessage()    {}
func (*WithdrawRecordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{24}
}

func (m *WithdrawRecordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRecordResp.Unmarshal(m, b)
}
func (m *WithdrawRecordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRecordResp.Marshal(b, m, deterministic)
}
func (m *WithdrawRecordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRecordResp.Merge(m, src)
}
func (m *WithdrawRecordResp) XXX_Size() int {
	return xxx_messageInfo_WithdrawRecordResp.Size(m)
}
func (m *WithdrawRecordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRecordResp.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRecordResp proto.InternalMessageInfo

func (m *WithdrawRecordResp) GetPageresp() *common.PageResp {
	if m != nil {
		return m.Pageresp
	}
	return nil
}

func (m *WithdrawRecordResp) GetWithdraws() []*Withdraw {
	if m != nil {
		return m.Withdraws
	}
	return nil
}

type MerchantOrdersReq struct {
	Pagereq              *common.PageReq `protobuf:"bytes,1,opt,name=pagereq,proto3" json:"pagereq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MerchantOrdersReq) Reset()         { *m = MerchantOrdersReq{} }
func (m *MerchantOrdersReq) String() string { return proto.CompactTextString(m) }
func (*MerchantOrdersReq) ProtoMessage()    {}
func (*MerchantOrdersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{25}
}

func (m *MerchantOrdersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantOrdersReq.Unmarshal(m, b)
}
func (m *MerchantOrdersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantOrdersReq.Marshal(b, m, deterministic)
}
func (m *MerchantOrdersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantOrdersReq.Merge(m, src)
}
func (m *MerchantOrdersReq) XXX_Size() int {
	return xxx_messageInfo_MerchantOrdersReq.Size(m)
}
func (m *MerchantOrdersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantOrdersReq.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantOrdersReq proto.InternalMessageInfo

func (m *MerchantOrdersReq) GetPagereq() *common.PageReq {
	if m != nil {
		return m.Pagereq
	}
	return nil
}

type MerchantOrdersResp struct {
	Pageresp             *common.PageResp     `protobuf:"bytes,1,opt,name=pageresp,proto3" json:"pageresp,omitempty"`
	OrderInfos           []*api.OrderInfoResp `protobuf:"bytes,2,rep,name=order_infos,json=orderInfos,proto3" json:"order_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MerchantOrdersResp) Reset()         { *m = MerchantOrdersResp{} }
func (m *MerchantOrdersResp) String() string { return proto.CompactTextString(m) }
func (*MerchantOrdersResp) ProtoMessage()    {}
func (*MerchantOrdersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb2bfc908a7bc8aa, []int{26}
}

func (m *MerchantOrdersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantOrdersResp.Unmarshal(m, b)
}
func (m *MerchantOrdersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantOrdersResp.Marshal(b, m, deterministic)
}
func (m *MerchantOrdersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantOrdersResp.Merge(m, src)
}
func (m *MerchantOrdersResp) XXX_Size() int {
	return xxx_messageInfo_MerchantOrdersResp.Size(m)
}
func (m *MerchantOrdersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantOrdersResp.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantOrdersResp proto.InternalMessageInfo

func (m *MerchantOrdersResp) GetPageresp() *common.PageResp {
	if m != nil {
		return m.Pageresp
	}
	return nil
}

func (m *MerchantOrdersResp) GetOrderInfos() []*api.OrderInfoResp {
	if m != nil {
		return m.OrderInfos
	}
	return nil
}

func init() {
	proto.RegisterEnum("open.MerchantApplyStatus", MerchantApplyStatus_name, MerchantApplyStatus_value)
	proto.RegisterEnum("open.ApplyResourceType", ApplyResourceType_name, ApplyResourceType_value)
	proto.RegisterEnum("open.WithdrawStatus", WithdrawStatus_name, WithdrawStatus_value)
	proto.RegisterType((*MerchantInfoReq)(nil), "open.MerchantInfoReq")
	proto.RegisterType((*MerchantInfoResp)(nil), "open.MerchantInfoResp")
	proto.RegisterType((*BindBankCardReq)(nil), "open.BindBankCardReq")
	proto.RegisterType((*BindBankCardResp)(nil), "open.BindBankCardResp")
	proto.RegisterType((*UnbindBankCardReq)(nil), "open.UnbindBankCardReq")
	proto.RegisterType((*UnbindBankCardResp)(nil), "open.UnbindBankCardResp")
	proto.RegisterType((*MerchantApplyReq)(nil), "open.MerchantApplyReq")
	proto.RegisterType((*MerchantApplyResp)(nil), "open.MerchantApplyResp")
	proto.RegisterType((*MerchantApplyInfoReq)(nil), "open.MerchantApplyInfoReq")
	proto.RegisterType((*MerchantApplyInfoResp)(nil), "open.MerchantApplyInfoResp")
	proto.RegisterType((*MerchantStationsReq)(nil), "open.MerchantStationsReq")
	proto.RegisterType((*MerchantStationsResp)(nil), "open.MerchantStationsResp")
	proto.RegisterType((*EvsesByStationReq)(nil), "open.EvsesByStationReq")
	proto.RegisterType((*EvsesByStationResp)(nil), "open.EvsesByStationResp")
	proto.RegisterType((*SetStationOperationStatusReq)(nil), "open.SetStationOperationStatusReq")
	proto.RegisterType((*SetStationOperationStatusResp)(nil), "open.SetStationOperationStatusResp")
	proto.RegisterType((*StationBindEvseReq)(nil), "open.StationBindEvseReq")
	proto.RegisterType((*StationBindEvseResp)(nil), "open.StationBindEvseResp")
	proto.RegisterType((*StationUnbindEvseReq)(nil), "open.StationUnbindEvseReq")
	proto.RegisterType((*StationUnbindEvseResp)(nil), "open.StationUnbindEvseResp")
	proto.RegisterType((*WithdrawApplyReq)(nil), "open.WithdrawApplyReq")
	proto.RegisterType((*WithdrawApplyResp)(nil), "open.WithdrawApplyResp")
	proto.RegisterType((*Withdraw)(nil), "open.Withdraw")
	proto.RegisterType((*WithdrawRecordReq)(nil), "open.WithdrawRecordReq")
	proto.RegisterType((*WithdrawRecordResp)(nil), "open.WithdrawRecordResp")
	proto.RegisterType((*MerchantOrdersReq)(nil), "open.MerchantOrdersReq")
	proto.RegisterType((*MerchantOrdersResp)(nil), "open.MerchantOrdersResp")
}

func init() { proto.RegisterFile("open.proto", fileDescriptor_bb2bfc908a7bc8aa) }

var fileDescriptor_bb2bfc908a7bc8aa = []byte{
	// 1388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x5b, 0x6f, 0xdb, 0xb6,
	0x17, 0xaf, 0x1c, 0xc7, 0x97, 0xe3, 0x5c, 0x14, 0xe6, 0xa6, 0x38, 0x4d, 0x93, 0xea, 0x0f, 0xfc,
	0x91, 0x05, 0x45, 0xb2, 0xa5, 0x5b, 0x31, 0x60, 0x17, 0x34, 0xc9, 0xd6, 0x35, 0xc0, 0xda, 0x06,
	0x4a, 0xbb, 0x01, 0x03, 0x06, 0x83, 0x91, 0x18, 0x47, 0xab, 0x45, 0xd2, 0xa4, 0x9c, 0x20, 0x0f,
	0xfb, 0x0e, 0x7b, 0xd8, 0x57, 0xd9, 0xf3, 0xf6, 0xa5, 0x36, 0xec, 0x6d, 0x03, 0x29, 0xd1, 0xb6,
	0x2e, 0x6e, 0xe3, 0xc7, 0xf9, 0x49, 0xe7, 0x77, 0x2e, 0x3a, 0x87, 0x47, 0x3c, 0x3f, 0xd2, 0x00,
	0x8c, 0x13, 0xba, 0xcf, 0x05, 0x8b, 0x19, 0xaa, 0xaa, 0xe7, 0xf6, 0x9c, 0xcf, 0xa2, 0x88, 0xa5,
	0x98, 0x92, 0x04, 0xe9, 0xde, 0xa4, 0x52, 0x13, 0xf3, 0x30, 0x79, 0x74, 0x97, 0x60, 0xf1, 0x05,
	0x11, 0xfe, 0x15, 0xa6, 0xf1, 0x29, 0xbd, 0x64, 0x1e, 0xe9, 0xbb, 0xbf, 0x57, 0xc0, 0xce, 0x62,
	0x92, 0xa3, 0x05, 0xa8, 0x84, 0x81, 0x63, 0xed, 0x58, 0xbb, 0x55, 0xaf, 0x12, 0x06, 0x08, 0x41,
	0x95, 0xe2, 0x88, 0x38, 0x95, 0x1d, 0x6b, 0xb7, 0xe9, 0xe9, 0x67, 0xb4, 0x02, 0xb3, 0x24, 0xc2,
	0x61, 0xcf, 0x99, 0xd1, 0x60, 0x22, 0x28, 0x94, 0x5f, 0x31, 0x4a, 0x9c, 0x6a, 0x82, 0x6a, 0x01,
	0xad, 0x43, 0x3d, 0x8c, 0xba, 0x9d, 0x81, 0xe8, 0x39, 0xb3, 0x1a, 0xaf, 0x85, 0x51, 0xf7, 0x8d,
	0xe8, 0x21, 0x07, 0xea, 0x17, 0xb8, 0x87, 0xa9, 0x4f, 0x9c, 0xda, 0x8e, 0xb5, 0x6b, 0x79, 0x46,
	0x44, 0xdb, 0xd0, 0xf2, 0x07, 0x32, 0x66, 0x11, 0x11, 0x9d, 0x30, 0x70, 0xea, 0x3a, 0x17, 0x30,
	0xd0, 0x69, 0x80, 0x1e, 0xc2, 0xdc, 0x05, 0xa6, 0x6f, 0x3b, 0xd8, 0xf7, 0xd9, 0x80, 0xc6, 0x4e,
	0x43, 0x07, 0x6e, 0x29, 0xec, 0x28, 0x81, 0xd0, 0x1e, 0x2c, 0x8d, 0x9b, 0x74, 0x74, 0x0d, 0x4d,
	0x6d, 0xb7, 0x38, 0x66, 0xf7, 0x52, 0x95, 0xb3, 0x09, 0x4d, 0x6d, 0xeb, 0xb3, 0x80, 0x38, 0xa0,
	0x6d, 0x1a, 0x0a, 0x38, 0x61, 0xc1, 0x48, 0xa9, 0x03, 0xb4, 0x46, 0x4a, 0xe5, 0xe9, 0xfe, 0x0c,
	0x8b, 0xc7, 0x21, 0x0d, 0x8e, 0x95, 0x31, 0x16, 0x81, 0x47, 0xfa, 0x85, 0xdc, 0xac, 0x3b, 0xe6,
	0x56, 0xb9, 0x43, 0x6e, 0x33, 0xd9, 0xdc, 0x5c, 0x04, 0x76, 0xf6, 0xf5, 0x92, 0xbb, 0x4f, 0x60,
	0xe9, 0x0d, 0xbd, 0x98, 0x3a, 0x29, 0x77, 0x05, 0x50, 0xde, 0x4f, 0x72, 0xf7, 0x0f, 0x6b, 0xf4,
	0x89, 0x1c, 0x71, 0xde, 0xbb, 0x55, 0xd1, 0x36, 0xa1, 0x39, 0x90, 0x44, 0x24, 0x79, 0x27, 0xa1,
	0x1a, 0x0a, 0xd0, 0x09, 0x6f, 0x40, 0x83, 0x5c, 0x4b, 0xd2, 0xa1, 0x83, 0x48, 0xd7, 0x34, 0xeb,
	0xd5, 0x95, 0xfc, 0x72, 0x10, 0xa1, 0x27, 0x30, 0x77, 0x4d, 0xae, 0x42, 0xbf, 0x47, 0x3a, 0xf1,
	0x2d, 0x4f, 0xca, 0x59, 0x38, 0x5c, 0xde, 0x4f, 0x3f, 0xd9, 0xef, 0x12, 0xdd, 0xeb, 0x5b, 0x4e,
	0xbc, 0xd6, 0xf5, 0x48, 0x40, 0x9f, 0xc3, 0xbc, 0x20, 0x92, 0x0d, 0x84, 0x9f, 0x3a, 0x56, 0xb5,
	0xe3, 0xfa, 0xbe, 0xde, 0x0b, 0x69, 0x5a, 0x89, 0x5e, 0x3b, 0xcf, 0x89, 0x31, 0xc9, 0x5d, 0x86,
	0xa5, 0x5c, 0x05, 0x92, 0xbb, 0x6b, 0xb0, 0x92, 0x01, 0xcd, 0x96, 0xf8, 0xdb, 0x82, 0xd5, 0x12,
	0x85, 0xe4, 0xff, 0xad, 0xa2, 0xd1, 0x47, 0x50, 0x93, 0x31, 0x8e, 0x07, 0x52, 0x6f, 0xba, 0x85,
	0xc3, 0x8d, 0xc4, 0x2d, 0x53, 0xda, 0xb9, 0x36, 0xf0, 0x52, 0x43, 0xf7, 0x29, 0x2c, 0x1b, 0xb5,
	0xd2, 0x84, 0x8c, 0x4a, 0xd5, 0xec, 0x0f, 0xa0, 0xce, 0x71, 0x97, 0x08, 0xd2, 0xd7, 0x55, 0xb7,
	0x0e, 0x17, 0xf7, 0xd3, 0x81, 0x73, 0x86, 0xbb, 0xc4, 0x23, 0x7d, 0xcf, 0xe8, 0x5d, 0x3a, 0x5a,
	0xd4, 0x51, 0x04, 0xc9, 0xd1, 0x23, 0x68, 0x24, 0x26, 0x92, 0xa7, 0x31, 0xec, 0x6c, 0x0c, 0xc9,
	0xbd, 0xa1, 0x05, 0xda, 0x85, 0x86, 0x4c, 0xbd, 0x9d, 0xca, 0xce, 0xcc, 0x6e, 0xeb, 0x70, 0x6e,
	0x5f, 0x8d, 0xb1, 0x34, 0xa4, 0x37, 0xd4, 0xba, 0x3f, 0xc2, 0xd2, 0xd7, 0xd7, 0x92, 0xc8, 0xe3,
	0x5b, 0xa3, 0x9b, 0x2a, 0x5f, 0xb4, 0x05, 0x90, 0xc6, 0x52, 0x63, 0xa6, 0xa2, 0xc7, 0x4c, 0x33,
	0x45, 0x4e, 0x03, 0xf7, 0x12, 0x50, 0x3e, 0xfc, 0xd4, 0xc5, 0xb8, 0x30, 0xab, 0x63, 0x0c, 0x2b,
	0x49, 0xdb, 0xae, 0x40, 0x2f, 0x51, 0xb9, 0x04, 0xee, 0x9f, 0x13, 0xb3, 0x62, 0xaf, 0x38, 0x11,
	0xfa, 0x21, 0xed, 0x4e, 0x21, 0x4d, 0x2b, 0x97, 0x26, 0xfa, 0x3f, 0x2c, 0x86, 0xb2, 0x13, 0xd2,
	0x0e, 0x33, 0xae, 0xba, 0x94, 0x86, 0x37, 0x1f, 0xca, 0xd3, 0x51, 0x3c, 0x77, 0x1b, 0xb6, 0xde,
	0xf1, 0x1a, 0xc9, 0xdd, 0xd7, 0x80, 0x52, 0xad, 0x1a, 0x2a, 0x3a, 0xc3, 0xf7, 0xbf, 0x7d, 0x1b,
	0x5a, 0x7d, 0xa1, 0x86, 0x53, 0x87, 0xe3, 0xf8, 0x2a, 0x9d, 0x62, 0x90, 0x40, 0x67, 0x38, 0xbe,
	0x72, 0x57, 0x61, 0xb9, 0x10, 0x55, 0x72, 0xf7, 0x25, 0xac, 0xa4, 0x70, 0x32, 0x75, 0xee, 0xf8,
	0xba, 0x75, 0xd0, 0x1b, 0x6b, 0xd4, 0xaf, 0x9a, 0x12, 0x4f, 0x03, 0x77, 0x1d, 0x56, 0x4b, 0xe2,
	0x49, 0xee, 0xee, 0x81, 0xfd, 0x7d, 0x18, 0x5f, 0x05, 0x02, 0xdf, 0x0c, 0x07, 0xd8, 0x1a, 0xd4,
	0x70, 0x34, 0x1c, 0x84, 0x96, 0x97, 0x4a, 0x6a, 0x54, 0xe4, 0x6c, 0x25, 0x77, 0xff, 0xac, 0x40,
	0xc3, 0xa0, 0x05, 0x76, 0xdc, 0x02, 0x88, 0x30, 0x55, 0xdd, 0x1e, 0xfb, 0x84, 0x52, 0xa4, 0x84,
	0xa8, 0x66, 0xee, 0x48, 0x06, 0xd5, 0x3b, 0x90, 0xc1, 0xec, 0xbb, 0x88, 0xaa, 0x96, 0x25, 0xaa,
	0xb1, 0x8a, 0xeb, 0xe3, 0x15, 0x23, 0x1b, 0x66, 0x2e, 0x09, 0xd1, 0x04, 0x6a, 0x79, 0xea, 0x11,
	0x3d, 0x1a, 0x4e, 0x8e, 0xa6, 0x9e, 0x1c, 0x2b, 0xc9, 0xe4, 0x30, 0x2b, 0x90, 0x1d, 0x1a, 0x2a,
	0xae, 0x20, 0x58, 0x32, 0x9a, 0xf2, 0x66, 0x2a, 0x21, 0x17, 0xe6, 0x19, 0xef, 0x8c, 0x2d, 0x4d,
	0x4b, 0x2f, 0x4d, 0x8b, 0xf1, 0x17, 0xc3, 0xc5, 0xd9, 0x02, 0xf0, 0x05, 0xc1, 0x31, 0x09, 0x3a,
	0x38, 0x76, 0xe6, 0x92, 0xb5, 0x4b, 0x91, 0xa3, 0xd8, 0xfd, 0x72, 0xd4, 0x0c, 0x8f, 0xf8, 0x2c,
	0x21, 0xb2, 0x29, 0xa6, 0x11, 0x07, 0x94, 0xf7, 0x9f, 0x7a, 0xfb, 0x3e, 0x82, 0xe6, 0x4d, 0x1a,
	0xc3, 0x6c, 0xe1, 0x85, 0xec, 0x7a, 0x78, 0x23, 0x03, 0x95, 0xb1, 0x99, 0x7f, 0xaf, 0x44, 0x40,
	0xc4, 0xb4, 0xf3, 0xf3, 0x06, 0x50, 0xde, 0x7f, 0xea, 0x8c, 0x1f, 0x43, 0x8b, 0x29, 0xdf, 0x4e,
	0x48, 0x2f, 0x99, 0xc9, 0x19, 0xe9, 0x01, 0xaa, 0x63, 0x1a, 0x3e, 0xf3, 0x80, 0x19, 0x51, 0xee,
	0xfd, 0x66, 0x8d, 0x66, 0xff, 0x18, 0x35, 0xa0, 0x07, 0xd0, 0x2e, 0x81, 0xdf, 0xd0, 0xb7, 0x94,
	0xdd, 0x50, 0xfb, 0xde, 0x04, 0xfd, 0x19, 0xa1, 0x41, 0x48, 0xbb, 0x36, 0x4c, 0xd2, 0x0b, 0xe6,
	0x13, 0x29, 0xed, 0x15, 0xb4, 0x03, 0xf7, 0x27, 0xeb, 0x49, 0x60, 0x3f, 0x40, 0xf7, 0xc1, 0x29,
	0xb1, 0x38, 0xe9, 0x31, 0x49, 0xec, 0xdd, 0xbd, 0x5f, 0x2a, 0xb0, 0x54, 0x60, 0x42, 0xb4, 0x09,
	0xeb, 0x05, 0x30, 0xc9, 0xd9, 0xbe, 0x87, 0xb6, 0x61, 0xb3, 0xa0, 0x3c, 0x61, 0x51, 0x44, 0x84,
	0x1f, 0xe2, 0x9e, 0x6d, 0xa1, 0x87, 0xb0, 0x55, 0x30, 0x78, 0x81, 0xe9, 0xe0, 0x12, 0xfb, 0xf1,
	0x40, 0x10, 0x61, 0x57, 0xd0, 0x16, 0x6c, 0x14, 0x4c, 0x92, 0x81, 0xca, 0x84, 0x3d, 0x53, 0xaa,
	0x7e, 0x8e, 0x45, 0x70, 0x83, 0x05, 0xb1, 0xab, 0x6a, 0x51, 0x0a, 0xea, 0x6f, 0xd8, 0x35, 0x11,
	0x11, 0xa1, 0xb1, 0x3d, 0x5b, 0xea, 0x7e, 0x26, 0xd4, 0x70, 0x8f, 0x6f, 0xed, 0x5a, 0xb9, 0x9a,
	0x08, 0xc9, 0x28, 0xee, 0xd9, 0xf5, 0xbd, 0x1e, 0x2c, 0x64, 0xb7, 0xaa, 0x5a, 0xc2, 0x2c, 0xd2,
	0x39, 0xa5, 0xa6, 0x05, 0xf7, 0xd0, 0x0e, 0x2c, 0xe7, 0xb4, 0xcf, 0x70, 0xd8, 0xb3, 0xff, 0xfa,
	0x27, 0xfd, 0x59, 0xa8, 0x0d, 0x6b, 0x39, 0x8b, 0xf3, 0x81, 0xaf, 0xbd, 0xe1, 0xf0, 0xd7, 0xfa,
	0xe8, 0x56, 0x71, 0x4e, 0xc4, 0x75, 0xe8, 0x13, 0xf4, 0x29, 0xcc, 0xea, 0x04, 0xd1, 0x5a, 0xc9,
	0x99, 0xc3, 0x23, 0xfd, 0xf6, 0x7a, 0x29, 0x2e, 0x39, 0xfa, 0x0a, 0x9a, 0xc3, 0x33, 0x17, 0x6a,
	0x97, 0x58, 0xa5, 0xa7, 0xb4, 0xf6, 0xe6, 0x44, 0x9d, 0xe4, 0xe8, 0x08, 0x1a, 0xe6, 0xf4, 0x81,
	0x72, 0xc7, 0x9e, 0xb1, 0x73, 0x4d, 0xbb, 0x3d, 0x49, 0x25, 0x39, 0x3a, 0x81, 0x85, 0x2c, 0xf3,
	0xa3, 0x34, 0xe7, 0xc2, 0x71, 0xa3, 0xed, 0x94, 0x2b, 0x24, 0x47, 0x01, 0x6c, 0x4c, 0xe4, 0x5b,
	0xe4, 0x26, 0x6e, 0xef, 0xe2, 0xfd, 0xf6, 0xff, 0xde, 0x6b, 0x23, 0x39, 0x7a, 0x06, 0x8b, 0x39,
	0x7a, 0x45, 0x69, 0x4a, 0x45, 0x2e, 0x6f, 0x6f, 0x4c, 0xd0, 0x48, 0x8e, 0xbe, 0x85, 0xa5, 0x02,
	0x7f, 0x9a, 0x1e, 0x94, 0x11, 0xb5, 0xe9, 0x41, 0x29, 0xe9, 0xa2, 0x4f, 0xa0, 0xaa, 0x9b, 0xb8,
	0x9a, 0x5d, 0x64, 0xd3, 0xbf, 0xb5, 0x32, 0x58, 0x72, 0xf4, 0x05, 0xcc, 0x8d, 0xdf, 0x67, 0x8c,
	0x7b, 0xee, 0x8a, 0x65, 0xdc, 0xf3, 0x57, 0x1f, 0xd5, 0xb6, 0xec, 0x15, 0xc6, 0xb4, 0xad, 0x70,
	0x21, 0x32, 0x6d, 0x2b, 0xde, 0x78, 0xd0, 0x53, 0x98, 0xcf, 0x9c, 0x01, 0xcc, 0x67, 0x9c, 0x3f,
	0x44, 0x98, 0xcf, 0xb8, 0x70, 0x60, 0x50, 0x69, 0x64, 0x89, 0x07, 0xe5, 0x4c, 0x87, 0x74, 0x66,
	0xd2, 0x28, 0xe1, 0xa9, 0xcf, 0xa0, 0x96, 0x70, 0x00, 0xca, 0x6d, 0x97, 0x21, 0xb3, 0x18, 0xe7,
	0x22, 0x65, 0x1c, 0x7f, 0xfc, 0x7c, 0xe6, 0x87, 0x0f, 0xbb, 0x61, 0xec, 0xcb, 0x48, 0xee, 0xff,
	0xc4, 0x6e, 0x25, 0xa3, 0xfd, 0x41, 0x48, 0x15, 0x6d, 0x1c, 0x28, 0xec, 0x40, 0xff, 0x25, 0xe0,
	0xb3, 0xde, 0x41, 0x97, 0xf5, 0x30, 0xed, 0x1e, 0xa8, 0x40, 0x17, 0x35, 0x8d, 0x3e, 0xfe, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x62, 0xf2, 0xde, 0xbc, 0x63, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MerchantServiceClient is the client API for MerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MerchantServiceClient interface {
	// 桩主申请
	Apply(ctx context.Context, in *MerchantApplyReq, opts ...grpc.CallOption) (*MerchantApplyResp, error)
	// 桩主申请信息
	ApplyInfo(ctx context.Context, in *MerchantApplyInfoReq, opts ...grpc.CallOption) (*MerchantApplyInfoResp, error)
	// 桩主站点列表
	Stations(ctx context.Context, in *MerchantStationsReq, opts ...grpc.CallOption) (*MerchantStationsResp, error)
	// 根据站点获取设备详情
	EvsesByStation(ctx context.Context, in *EvsesByStationReq, opts ...grpc.CallOption) (*EvsesByStationResp, error)
	// 设置站点运营商状态
	SetStationOperationStatus(ctx context.Context, in *SetStationOperationStatusReq, opts ...grpc.CallOption) (*SetStationOperationStatusResp, error)
	// 站点绑定设备
	StationBindEvse(ctx context.Context, in *StationBindEvseReq, opts ...grpc.CallOption) (*StationBindEvseResp, error)
	// 站点解绑设备
	StationUnbindEvse(ctx context.Context, in *StationUnbindEvseReq, opts ...grpc.CallOption) (*StationUnbindEvseResp, error)
	// 桩主基本信息
	Info(ctx context.Context, in *MerchantInfoReq, opts ...grpc.CallOption) (*MerchantInfoResp, error)
	// 绑定银行卡
	BindBankCard(ctx context.Context, in *BindBankCardReq, opts ...grpc.CallOption) (*BindBankCardResp, error)
	// 解绑银行卡
	UnbindBankCard(ctx context.Context, in *UnbindBankCardReq, opts ...grpc.CallOption) (*UnbindBankCardResp, error)
	// 提现申请
	WithdrawApply(ctx context.Context, in *WithdrawApplyReq, opts ...grpc.CallOption) (*WithdrawApplyResp, error)
	// 提现记录
	WithdrawRecord(ctx context.Context, in *WithdrawRecordReq, opts ...grpc.CallOption) (*WithdrawRecordResp, error)
	// 订单
	Orders(ctx context.Context, in *MerchantOrdersReq, opts ...grpc.CallOption) (*MerchantOrdersResp, error)
}

type merchantServiceClient struct {
	cc *grpc.ClientConn
}

func NewMerchantServiceClient(cc *grpc.ClientConn) MerchantServiceClient {
	return &merchantServiceClient{cc}
}

func (c *merchantServiceClient) Apply(ctx context.Context, in *MerchantApplyReq, opts ...grpc.CallOption) (*MerchantApplyResp, error) {
	out := new(MerchantApplyResp)
	err := c.cc.Invoke(ctx, "/open.MerchantService/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) ApplyInfo(ctx context.Context, in *MerchantApplyInfoReq, opts ...grpc.CallOption) (*MerchantApplyInfoResp, error) {
	out := new(MerchantApplyInfoResp)
	err := c.cc.Invoke(ctx, "/open.MerchantService/ApplyInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) Stations(ctx context.Context, in *MerchantStationsReq, opts ...grpc.CallOption) (*MerchantStationsResp, error) {
	out := new(MerchantStationsResp)
	err := c.cc.Invoke(ctx, "/open.MerchantService/Stations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) EvsesByStation(ctx context.Context, in *EvsesByStationReq, opts ...grpc.CallOption) (*EvsesByStationResp, error) {
	out := new(EvsesByStationResp)
	err := c.cc.Invoke(ctx, "/open.MerchantService/EvsesByStation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) SetStationOperationStatus(ctx context.Context, in *SetStationOperationStatusReq, opts ...grpc.CallOption) (*SetStationOperationStatusResp, error) {
	out := new(SetStationOperationStatusResp)
	err := c.cc.Invoke(ctx, "/open.MerchantService/SetStationOperationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) StationBindEvse(ctx context.Context, in *StationBindEvseReq, opts ...grpc.CallOption) (*StationBindEvseResp, error) {
	out := new(StationBindEvseResp)
	err := c.cc.Invoke(ctx, "/open.MerchantService/StationBindEvse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) StationUnbindEvse(ctx context.Context, in *StationUnbindEvseReq, opts ...grpc.CallOption) (*StationUnbindEvseResp, error) {
	out := new(StationUnbindEvseResp)
	err := c.cc.Invoke(ctx, "/open.MerchantService/StationUnbindEvse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) Info(ctx context.Context, in *MerchantInfoReq, opts ...grpc.CallOption) (*MerchantInfoResp, error) {
	out := new(MerchantInfoResp)
	err := c.cc.Invoke(ctx, "/open.MerchantService/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) BindBankCard(ctx context.Context, in *BindBankCardReq, opts ...grpc.CallOption) (*BindBankCardResp, error) {
	out := new(BindBankCardResp)
	err := c.cc.Invoke(ctx, "/open.MerchantService/BindBankCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) UnbindBankCard(ctx context.Context, in *UnbindBankCardReq, opts ...grpc.CallOption) (*UnbindBankCardResp, error) {
	out := new(UnbindBankCardResp)
	err := c.cc.Invoke(ctx, "/open.MerchantService/UnbindBankCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) WithdrawApply(ctx context.Context, in *WithdrawApplyReq, opts ...grpc.CallOption) (*WithdrawApplyResp, error) {
	out := new(WithdrawApplyResp)
	err := c.cc.Invoke(ctx, "/open.MerchantService/WithdrawApply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) WithdrawRecord(ctx context.Context, in *WithdrawRecordReq, opts ...grpc.CallOption) (*WithdrawRecordResp, error) {
	out := new(WithdrawRecordResp)
	err := c.cc.Invoke(ctx, "/open.MerchantService/WithdrawRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) Orders(ctx context.Context, in *MerchantOrdersReq, opts ...grpc.CallOption) (*MerchantOrdersResp, error) {
	out := new(MerchantOrdersResp)
	err := c.cc.Invoke(ctx, "/open.MerchantService/Orders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantServiceServer is the server API for MerchantService service.
type MerchantServiceServer interface {
	// 桩主申请
	Apply(context.Context, *MerchantApplyReq) (*MerchantApplyResp, error)
	// 桩主申请信息
	ApplyInfo(context.Context, *MerchantApplyInfoReq) (*MerchantApplyInfoResp, error)
	// 桩主站点列表
	Stations(context.Context, *MerchantStationsReq) (*MerchantStationsResp, error)
	// 根据站点获取设备详情
	EvsesByStation(context.Context, *EvsesByStationReq) (*EvsesByStationResp, error)
	// 设置站点运营商状态
	SetStationOperationStatus(context.Context, *SetStationOperationStatusReq) (*SetStationOperationStatusResp, error)
	// 站点绑定设备
	StationBindEvse(context.Context, *StationBindEvseReq) (*StationBindEvseResp, error)
	// 站点解绑设备
	StationUnbindEvse(context.Context, *StationUnbindEvseReq) (*StationUnbindEvseResp, error)
	// 桩主基本信息
	Info(context.Context, *MerchantInfoReq) (*MerchantInfoResp, error)
	// 绑定银行卡
	BindBankCard(context.Context, *BindBankCardReq) (*BindBankCardResp, error)
	// 解绑银行卡
	UnbindBankCard(context.Context, *UnbindBankCardReq) (*UnbindBankCardResp, error)
	// 提现申请
	WithdrawApply(context.Context, *WithdrawApplyReq) (*WithdrawApplyResp, error)
	// 提现记录
	WithdrawRecord(context.Context, *WithdrawRecordReq) (*WithdrawRecordResp, error)
	// 订单
	Orders(context.Context, *MerchantOrdersReq) (*MerchantOrdersResp, error)
}

func RegisterMerchantServiceServer(s *grpc.Server, srv MerchantServiceServer) {
	s.RegisterService(&_MerchantService_serviceDesc, srv)
}

func _MerchantService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantApplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/open.MerchantService/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).Apply(ctx, req.(*MerchantApplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_ApplyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantApplyInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).ApplyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/open.MerchantService/ApplyInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).ApplyInfo(ctx, req.(*MerchantApplyInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_Stations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantStationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).Stations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/open.MerchantService/Stations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).Stations(ctx, req.(*MerchantStationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_EvsesByStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvsesByStationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).EvsesByStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/open.MerchantService/EvsesByStation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).EvsesByStation(ctx, req.(*EvsesByStationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_SetStationOperationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStationOperationStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).SetStationOperationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/open.MerchantService/SetStationOperationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).SetStationOperationStatus(ctx, req.(*SetStationOperationStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_StationBindEvse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StationBindEvseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).StationBindEvse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/open.MerchantService/StationBindEvse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).StationBindEvse(ctx, req.(*StationBindEvseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_StationUnbindEvse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StationUnbindEvseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).StationUnbindEvse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/open.MerchantService/StationUnbindEvse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).StationUnbindEvse(ctx, req.(*StationUnbindEvseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/open.MerchantService/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).Info(ctx, req.(*MerchantInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_BindBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindBankCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).BindBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/open.MerchantService/BindBankCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).BindBankCard(ctx, req.(*BindBankCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_UnbindBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindBankCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).UnbindBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/open.MerchantService/UnbindBankCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).UnbindBankCard(ctx, req.(*UnbindBankCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_WithdrawApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawApplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).WithdrawApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/open.MerchantService/WithdrawApply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).WithdrawApply(ctx, req.(*WithdrawApplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_WithdrawRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).WithdrawRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/open.MerchantService/WithdrawRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).WithdrawRecord(ctx, req.(*WithdrawRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_Orders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).Orders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/open.MerchantService/Orders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).Orders(ctx, req.(*MerchantOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MerchantService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "open.MerchantService",
	HandlerType: (*MerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _MerchantService_Apply_Handler,
		},
		{
			MethodName: "ApplyInfo",
			Handler:    _MerchantService_ApplyInfo_Handler,
		},
		{
			MethodName: "Stations",
			Handler:    _MerchantService_Stations_Handler,
		},
		{
			MethodName: "EvsesByStation",
			Handler:    _MerchantService_EvsesByStation_Handler,
		},
		{
			MethodName: "SetStationOperationStatus",
			Handler:    _MerchantService_SetStationOperationStatus_Handler,
		},
		{
			MethodName: "StationBindEvse",
			Handler:    _MerchantService_StationBindEvse_Handler,
		},
		{
			MethodName: "StationUnbindEvse",
			Handler:    _MerchantService_StationUnbindEvse_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _MerchantService_Info_Handler,
		},
		{
			MethodName: "BindBankCard",
			Handler:    _MerchantService_BindBankCard_Handler,
		},
		{
			MethodName: "UnbindBankCard",
			Handler:    _MerchantService_UnbindBankCard_Handler,
		},
		{
			MethodName: "WithdrawApply",
			Handler:    _MerchantService_WithdrawApply_Handler,
		},
		{
			MethodName: "WithdrawRecord",
			Handler:    _MerchantService_WithdrawRecord_Handler,
		},
		{
			MethodName: "Orders",
			Handler:    _MerchantService_Orders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "open.proto",
}
