// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付类型
type PayMode int32

const (
	PayMode_PM_Unknown     PayMode = 0    // 未知支付
	PayMode_PM_Online      PayMode = 1    // 在线支付
	PayMode_PM_Group       PayMode = 2    // 集团支付
	PayMode_PM_IdCard      PayMode = 3    // 鉴权卡
	PayMode_PM_UserBalance PayMode = 4    // 用户余额
	PayMode_PM_WalletCard  PayMode = 5    // 钱包卡
	PayMode_PM_Manul       PayMode = 6    // 后台
	PayMode_PM_VIN         PayMode = 7    // VIN
	PayMode_PM_Partner     PayMode = 1000 // 第三方平台
)

// Enum value maps for PayMode.
var (
	PayMode_name = map[int32]string{
		0:    "PM_Unknown",
		1:    "PM_Online",
		2:    "PM_Group",
		3:    "PM_IdCard",
		4:    "PM_UserBalance",
		5:    "PM_WalletCard",
		6:    "PM_Manul",
		7:    "PM_VIN",
		1000: "PM_Partner",
	}
	PayMode_value = map[string]int32{
		"PM_Unknown":     0,
		"PM_Online":      1,
		"PM_Group":       2,
		"PM_IdCard":      3,
		"PM_UserBalance": 4,
		"PM_WalletCard":  5,
		"PM_Manul":       6,
		"PM_VIN":         7,
		"PM_Partner":     1000,
	}
)

func (x PayMode) Enum() *PayMode {
	p := new(PayMode)
	*p = x
	return p
}

func (x PayMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayMode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (PayMode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x PayMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayMode.Descriptor instead.
func (PayMode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// 支付渠道，一个支付类型对应多个支付渠道
type PayChannel int32

const (
	PayChannel_PC_Unknown     PayChannel = 0  // 未知
	PayChannel_PC_AliPay      PayChannel = 1  // 支付宝
	PayChannel_PC_WechatPay   PayChannel = 2  // 微信
	PayChannel_PC_UserBalance PayChannel = 3  // 用户余额
	PayChannel_PC_CardBalance PayChannel = 4  // 卡余额
	PayChannel_PC_Group       PayChannel = 5  // 集团支付
	PayChannel_PC_Bank        PayChannel = 6  // 银行
	PayChannel_PC_WalletCard  PayChannel = 7  // 钱包卡
	PayChannel_PC_Manul       PayChannel = 8  // 后台操作支付
	PayChannel_PC_VIN         PayChannel = 15 // vin
)

// Enum value maps for PayChannel.
var (
	PayChannel_name = map[int32]string{
		0:  "PC_Unknown",
		1:  "PC_AliPay",
		2:  "PC_WechatPay",
		3:  "PC_UserBalance",
		4:  "PC_CardBalance",
		5:  "PC_Group",
		6:  "PC_Bank",
		7:  "PC_WalletCard",
		8:  "PC_Manul",
		15: "PC_VIN",
	}
	PayChannel_value = map[string]int32{
		"PC_Unknown":     0,
		"PC_AliPay":      1,
		"PC_WechatPay":   2,
		"PC_UserBalance": 3,
		"PC_CardBalance": 4,
		"PC_Group":       5,
		"PC_Bank":        6,
		"PC_WalletCard":  7,
		"PC_Manul":       8,
		"PC_VIN":         15,
	}
)

func (x PayChannel) Enum() *PayChannel {
	p := new(PayChannel)
	*p = x
	return p
}

func (x PayChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (PayChannel) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x PayChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayChannel.Descriptor instead.
func (PayChannel) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type RefundMode int32

const (
	RefundMode_RM_Unknown     RefundMode = 0 //
	RefundMode_RM_BackTrack   RefundMode = 1 // 原路退回
	RefundMode_RM_UserBalance RefundMode = 2 // 退回到用户余额
)

// Enum value maps for RefundMode.
var (
	RefundMode_name = map[int32]string{
		0: "RM_Unknown",
		1: "RM_BackTrack",
		2: "RM_UserBalance",
	}
	RefundMode_value = map[string]int32{
		"RM_Unknown":     0,
		"RM_BackTrack":   1,
		"RM_UserBalance": 2,
	}
)

func (x RefundMode) Enum() *RefundMode {
	p := new(RefundMode)
	*p = x
	return p
}

func (x RefundMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefundMode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (RefundMode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x RefundMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefundMode.Descriptor instead.
func (RefundMode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type AuthModeChannel int32

const (
	AuthModeChannel_AMC_Unknown            AuthModeChannel = 0    //
	AuthModeChannel_AMC_App                AuthModeChannel = 1    // app
	AuthModeChannel_AMC_WechatService      AuthModeChannel = 2    // 微信服务号
	AuthModeChannel_AMC_ALiService         AuthModeChannel = 3    // 支付宝服务号
	AuthModeChannel_AMC_WechatSmallRoutine AuthModeChannel = 4    // 微信小程序
	AuthModeChannel_AMC_AliSmallRoutine    AuthModeChannel = 5    // 支付宝小程序
	AuthModeChannel_AMC_LocalPlug          AuthModeChannel = 6    // 本地即插即充启动
	AuthModeChannel_AMC_LocalAdmin         AuthModeChannel = 7    // 本地管理员启动
	AuthModeChannel_AMC_LocalIdentityCard  AuthModeChannel = 8    // 鉴权卡刷卡本地鉴权启动
	AuthModeChannel_AMC_OnlineIdentityCard AuthModeChannel = 9    // 鉴权卡刷卡在线鉴权启动
	AuthModeChannel_AMC_LocalWalletCard    AuthModeChannel = 10   // 本地钱包卡刷卡启动
	AuthModeChannel_AMC_LocalVIN           AuthModeChannel = 11   // 车辆VIN本地鉴权启动
	AuthModeChannel_AMC_OnlineVIN          AuthModeChannel = 12   // 车辆VIN在线鉴权启动
	AuthModeChannel_AMC_Bluetooth          AuthModeChannel = 13   // 本地通过蓝牙启动
	AuthModeChannel_AMC_MAC                AuthModeChannel = 14   // 本地通过输入校验码启动
	AuthModeChannel_AMC_RemoteAdmin        AuthModeChannel = 15   // 远程管理员启动
	AuthModeChannel_AMC_Partner            AuthModeChannel = 1000 // 第三方
)

// Enum value maps for AuthModeChannel.
var (
	AuthModeChannel_name = map[int32]string{
		0:    "AMC_Unknown",
		1:    "AMC_App",
		2:    "AMC_WechatService",
		3:    "AMC_ALiService",
		4:    "AMC_WechatSmallRoutine",
		5:    "AMC_AliSmallRoutine",
		6:    "AMC_LocalPlug",
		7:    "AMC_LocalAdmin",
		8:    "AMC_LocalIdentityCard",
		9:    "AMC_OnlineIdentityCard",
		10:   "AMC_LocalWalletCard",
		11:   "AMC_LocalVIN",
		12:   "AMC_OnlineVIN",
		13:   "AMC_Bluetooth",
		14:   "AMC_MAC",
		15:   "AMC_RemoteAdmin",
		1000: "AMC_Partner",
	}
	AuthModeChannel_value = map[string]int32{
		"AMC_Unknown":            0,
		"AMC_App":                1,
		"AMC_WechatService":      2,
		"AMC_ALiService":         3,
		"AMC_WechatSmallRoutine": 4,
		"AMC_AliSmallRoutine":    5,
		"AMC_LocalPlug":          6,
		"AMC_LocalAdmin":         7,
		"AMC_LocalIdentityCard":  8,
		"AMC_OnlineIdentityCard": 9,
		"AMC_LocalWalletCard":    10,
		"AMC_LocalVIN":           11,
		"AMC_OnlineVIN":          12,
		"AMC_Bluetooth":          13,
		"AMC_MAC":                14,
		"AMC_RemoteAdmin":        15,
		"AMC_Partner":            1000,
	}
)

func (x AuthModeChannel) Enum() *AuthModeChannel {
	p := new(AuthModeChannel)
	*p = x
	return p
}

func (x AuthModeChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthModeChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (AuthModeChannel) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x AuthModeChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthModeChannel.Descriptor instead.
func (AuthModeChannel) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

type CustomerRegChannel int32

const (
	CustomerRegChannel_CRC_Unknown            CustomerRegChannel = 0    //
	CustomerRegChannel_CRC_App                CustomerRegChannel = 1    // app
	CustomerRegChannel_CRC_WechatService      CustomerRegChannel = 2    // 微信服务号
	CustomerRegChannel_CRC_ALiService         CustomerRegChannel = 3    // 支付宝服务号
	CustomerRegChannel_CRC_WechatSmallRoutine CustomerRegChannel = 4    // 微信小程序
	CustomerRegChannel_CRC_AliSmallRoutine    CustomerRegChannel = 5    // 支付宝小程序
	CustomerRegChannel_CRC_Partner            CustomerRegChannel = 1000 // 第三方
)

// Enum value maps for CustomerRegChannel.
var (
	CustomerRegChannel_name = map[int32]string{
		0:    "CRC_Unknown",
		1:    "CRC_App",
		2:    "CRC_WechatService",
		3:    "CRC_ALiService",
		4:    "CRC_WechatSmallRoutine",
		5:    "CRC_AliSmallRoutine",
		1000: "CRC_Partner",
	}
	CustomerRegChannel_value = map[string]int32{
		"CRC_Unknown":            0,
		"CRC_App":                1,
		"CRC_WechatService":      2,
		"CRC_ALiService":         3,
		"CRC_WechatSmallRoutine": 4,
		"CRC_AliSmallRoutine":    5,
		"CRC_Partner":            1000,
	}
)

func (x CustomerRegChannel) Enum() *CustomerRegChannel {
	p := new(CustomerRegChannel)
	*p = x
	return p
}

func (x CustomerRegChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomerRegChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[4].Descriptor()
}

func (CustomerRegChannel) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[4]
}

func (x CustomerRegChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomerRegChannel.Descriptor instead.
func (CustomerRegChannel) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

type Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` //状态码,非0为异常，0位正常
	Err  string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`    //错误描述
	Obj  []byte `protobuf:"bytes,3,opt,name=obj,proto3" json:"obj,omitempty"`    //真正的返回对象
}

func (x *Resp) Reset() {
	*x = Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Resp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Resp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *Resp) GetObj() []byte {
	if x != nil {
		return x.Obj
	}
	return nil
}

type PageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`   // 页码，从1开始
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 每页显示数量，
}

func (x *PageReq) Reset() {
	*x = PageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReq) ProtoMessage() {}

func (x *PageReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReq.ProtoReflect.Descriptor instead.
func (*PageReq) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalPage int32 `protobuf:"varint,1,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	TotalRows int32 `protobuf:"varint,2,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
}

func (x *PageResp) Reset() {
	*x = PageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResp) ProtoMessage() {}

func (x *PageResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResp.ProtoReflect.Descriptor instead.
func (*PageResp) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *PageResp) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *PageResp) GetTotalRows() int32 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

type SearchFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterName string `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	FilterVal  string `protobuf:"bytes,2,opt,name=filter_val,json=filterVal,proto3" json:"filter_val,omitempty"`
	FilterOp   string `protobuf:"bytes,3,opt,name=filter_op,json=filterOp,proto3" json:"filter_op,omitempty"` // 过滤类型:(=、!=、LIKE、NOT LIKE、>、<、>=<=、FIND_IN_SET、IN、NOT IN、BETWEEN、NOT BETWEEN、RANGE、NOT RANGE、NULL、NOT NULL、)
}

func (x *SearchFilter) Reset() {
	*x = SearchFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilter) ProtoMessage() {}

func (x *SearchFilter) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilter.ProtoReflect.Descriptor instead.
func (*SearchFilter) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *SearchFilter) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

func (x *SearchFilter) GetFilterVal() string {
	if x != nil {
		return x.FilterVal
	}
	return ""
}

func (x *SearchFilter) GetFilterOp() string {
	if x != nil {
		return x.FilterOp
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x3e, 0x0a, 0x04, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x62, 0x6a, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x6f, 0x62, 0x6a, 0x22, 0x33, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x48, 0x0a, 0x08, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x72, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x52, 0x6f, 0x77, 0x73, 0x22, 0x6b, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x5f, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x56, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f,
	0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x4f, 0x70, 0x2a, 0x97, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0e,
	0x0a, 0x0a, 0x50, 0x4d, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x50, 0x4d, 0x5f, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x50, 0x4d, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x50,
	0x4d, 0x5f, 0x49, 0x64, 0x43, 0x61, 0x72, 0x64, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x4d,
	0x5f, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x10, 0x04, 0x12, 0x11,
	0x0a, 0x0d, 0x50, 0x4d, 0x5f, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x10,
	0x05, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x4d, 0x5f, 0x4d, 0x61, 0x6e, 0x75, 0x6c, 0x10, 0x06, 0x12,
	0x0a, 0x0a, 0x06, 0x50, 0x4d, 0x5f, 0x56, 0x49, 0x4e, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0a, 0x50,
	0x4d, 0x5f, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x10, 0xe8, 0x07, 0x2a, 0xad, 0x01, 0x0a,
	0x0a, 0x50, 0x61, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x0a, 0x50,
	0x43, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50,
	0x43, 0x5f, 0x41, 0x6c, 0x69, 0x50, 0x61, 0x79, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x43,
	0x5f, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x50, 0x61, 0x79, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e,
	0x50, 0x43, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x10, 0x03,
	0x12, 0x12, 0x0a, 0x0e, 0x50, 0x43, 0x5f, 0x43, 0x61, 0x72, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x43, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x43, 0x5f, 0x42, 0x61, 0x6e, 0x6b, 0x10, 0x06, 0x12,
	0x11, 0x0a, 0x0d, 0x50, 0x43, 0x5f, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x43, 0x5f, 0x4d, 0x61, 0x6e, 0x75, 0x6c, 0x10, 0x08,
	0x12, 0x0a, 0x0a, 0x06, 0x50, 0x43, 0x5f, 0x56, 0x49, 0x4e, 0x10, 0x0f, 0x2a, 0x42, 0x0a, 0x0a,
	0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x4d,
	0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x4d,
	0x5f, 0x42, 0x61, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e,
	0x52, 0x4d, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x10, 0x02,
	0x2a, 0xf2, 0x02, 0x0a, 0x0f, 0x41, 0x75, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x4d, 0x43, 0x5f, 0x55, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x4d, 0x43, 0x5f, 0x41, 0x70, 0x70,
	0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x4d, 0x43, 0x5f, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x4d, 0x43,
	0x5f, 0x41, 0x4c, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x10, 0x03, 0x12, 0x1a, 0x0a,
	0x16, 0x41, 0x4d, 0x43, 0x5f, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x53, 0x6d, 0x61, 0x6c, 0x6c,
	0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x4d, 0x43,
	0x5f, 0x41, 0x6c, 0x69, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65,
	0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x4d, 0x43, 0x5f, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50,
	0x6c, 0x75, 0x67, 0x10, 0x06, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x4d, 0x43, 0x5f, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x10, 0x07, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x4d, 0x43,
	0x5f, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x61,
	0x72, 0x64, 0x10, 0x08, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x4d, 0x43, 0x5f, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64, 0x10, 0x09,
	0x12, 0x17, 0x0a, 0x13, 0x41, 0x4d, 0x43, 0x5f, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x10, 0x0a, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x4d, 0x43,
	0x5f, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x56, 0x49, 0x4e, 0x10, 0x0b, 0x12, 0x11, 0x0a, 0x0d, 0x41,
	0x4d, 0x43, 0x5f, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x49, 0x4e, 0x10, 0x0c, 0x12, 0x11,
	0x0a, 0x0d, 0x41, 0x4d, 0x43, 0x5f, 0x42, 0x6c, 0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74, 0x68, 0x10,
	0x0d, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x4d, 0x43, 0x5f, 0x4d, 0x41, 0x43, 0x10, 0x0e, 0x12, 0x13,
	0x0a, 0x0f, 0x41, 0x4d, 0x43, 0x5f, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x10, 0x0f, 0x12, 0x10, 0x0a, 0x0b, 0x41, 0x4d, 0x43, 0x5f, 0x50, 0x61, 0x72, 0x74, 0x6e,
	0x65, 0x72, 0x10, 0xe8, 0x07, 0x2a, 0xa4, 0x01, 0x0a, 0x12, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x52, 0x65, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x0f, 0x0a, 0x0b,
	0x43, 0x52, 0x43, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x43, 0x52, 0x43, 0x5f, 0x41, 0x70, 0x70, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x52,
	0x43, 0x5f, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x10,
	0x02, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x52, 0x43, 0x5f, 0x41, 0x4c, 0x69, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x10, 0x03, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x52, 0x43, 0x5f, 0x57, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x10,
	0x04, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x52, 0x43, 0x5f, 0x41, 0x6c, 0x69, 0x53, 0x6d, 0x61, 0x6c,
	0x6c, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0b, 0x43, 0x52,
	0x43, 0x5f, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x10, 0xe8, 0x07, 0x42, 0x2e, 0x48, 0x03,
	0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x6f, 0x74,
	0x6f, 0x64, 0x69, 0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_goTypes = []interface{}{
	(PayMode)(0),            // 0: common.PayMode
	(PayChannel)(0),         // 1: common.PayChannel
	(RefundMode)(0),         // 2: common.RefundMode
	(AuthModeChannel)(0),    // 3: common.AuthModeChannel
	(CustomerRegChannel)(0), // 4: common.CustomerRegChannel
	(*Resp)(nil),            // 5: common.Resp
	(*PageReq)(nil),         // 6: common.PageReq
	(*PageResp)(nil),        // 7: common.PageResp
	(*SearchFilter)(nil),    // 8: common.SearchFilter
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
