// Code generated by protoc-gen-go. DO NOT EDIT.
// source: group-admin.proto

package group_admin

import (
	context "context"
	fmt "fmt"
	common "github.com/Kotodian/protocol/golang/common"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupState int32

const (
	GroupState_Normal GroupState = 0
	GroupState_Block  GroupState = 1
)

var GroupState_name = map[int32]string{
	0: "Normal",
	1: "Block",
}

var GroupState_value = map[string]int32{
	"Normal": 0,
	"Block":  1,
}

func (x GroupState) String() string {
	return proto.EnumName(GroupState_name, int32(x))
}

func (GroupState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{0}
}

// 充值方式
type ChargeMode int32

const (
	ChargeMode_ChargeMode_Unknown ChargeMode = 0
	ChargeMode_ChargeMode_Bank    ChargeMode = 1
	ChargeMode_ChargeMode_System  ChargeMode = 2
)

var ChargeMode_name = map[int32]string{
	0: "ChargeMode_Unknown",
	1: "ChargeMode_Bank",
	2: "ChargeMode_System",
}

var ChargeMode_value = map[string]int32{
	"ChargeMode_Unknown": 0,
	"ChargeMode_Bank":    1,
	"ChargeMode_System":  2,
}

func (x ChargeMode) String() string {
	return proto.EnumName(ChargeMode_name, int32(x))
}

func (ChargeMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{1}
}

type GroupMember struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`
	CustomerId           uint64   `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty,string"`
	GroupId              uint64   `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty,string"`
	OperatorId           uint64   `protobuf:"varint,4,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty,string"`
	IsBlock              bool     `protobuf:"varint,5,opt,name=IsBlock,proto3" json:"IsBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMember) Reset()         { *m = GroupMember{} }
func (m *GroupMember) String() string { return proto.CompactTextString(m) }
func (*GroupMember) ProtoMessage()    {}
func (*GroupMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{0}
}

func (m *GroupMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMember.Unmarshal(m, b)
}
func (m *GroupMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMember.Marshal(b, m, deterministic)
}
func (m *GroupMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMember.Merge(m, src)
}
func (m *GroupMember) XXX_Size() int {
	return xxx_messageInfo_GroupMember.Size(m)
}
func (m *GroupMember) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMember.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMember proto.InternalMessageInfo

func (m *GroupMember) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GroupMember) GetCustomerId() uint64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *GroupMember) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupMember) GetOperatorId() uint64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func (m *GroupMember) GetIsBlock() bool {
	if m != nil {
		return m.IsBlock
	}
	return false
}

type GetMemberInfoByCustomerReq struct {
	CustomerId           uint64   `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty,string"`
	OperatorId           uint64   `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty,string"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemberInfoByCustomerReq) Reset()         { *m = GetMemberInfoByCustomerReq{} }
func (m *GetMemberInfoByCustomerReq) String() string { return proto.CompactTextString(m) }
func (*GetMemberInfoByCustomerReq) ProtoMessage()    {}
func (*GetMemberInfoByCustomerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{1}
}

func (m *GetMemberInfoByCustomerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberInfoByCustomerReq.Unmarshal(m, b)
}
func (m *GetMemberInfoByCustomerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberInfoByCustomerReq.Marshal(b, m, deterministic)
}
func (m *GetMemberInfoByCustomerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberInfoByCustomerReq.Merge(m, src)
}
func (m *GetMemberInfoByCustomerReq) XXX_Size() int {
	return xxx_messageInfo_GetMemberInfoByCustomerReq.Size(m)
}
func (m *GetMemberInfoByCustomerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberInfoByCustomerReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberInfoByCustomerReq proto.InternalMessageInfo

func (m *GetMemberInfoByCustomerReq) GetCustomerId() uint64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *GetMemberInfoByCustomerReq) GetOperatorId() uint64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type GetMemberInfoByCustomerResp struct {
	MemberInfo           *GroupMember `protobuf:"bytes,1,opt,name=member_info,json=memberInfo,proto3" json:"member_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetMemberInfoByCustomerResp) Reset()         { *m = GetMemberInfoByCustomerResp{} }
func (m *GetMemberInfoByCustomerResp) String() string { return proto.CompactTextString(m) }
func (*GetMemberInfoByCustomerResp) ProtoMessage()    {}
func (*GetMemberInfoByCustomerResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{2}
}

func (m *GetMemberInfoByCustomerResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberInfoByCustomerResp.Unmarshal(m, b)
}
func (m *GetMemberInfoByCustomerResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberInfoByCustomerResp.Marshal(b, m, deterministic)
}
func (m *GetMemberInfoByCustomerResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberInfoByCustomerResp.Merge(m, src)
}
func (m *GetMemberInfoByCustomerResp) XXX_Size() int {
	return xxx_messageInfo_GetMemberInfoByCustomerResp.Size(m)
}
func (m *GetMemberInfoByCustomerResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberInfoByCustomerResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberInfoByCustomerResp proto.InternalMessageInfo

func (m *GetMemberInfoByCustomerResp) GetMemberInfo() *GroupMember {
	if m != nil {
		return m.MemberInfo
	}
	return nil
}

type UpdateGroupReq struct {
	OperatorId           uint64   `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty,string"`
	GroupId              uint64   `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty,string"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupReq) Reset()         { *m = UpdateGroupReq{} }
func (m *UpdateGroupReq) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupReq) ProtoMessage()    {}
func (*UpdateGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{3}
}

func (m *UpdateGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupReq.Unmarshal(m, b)
}
func (m *UpdateGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupReq.Marshal(b, m, deterministic)
}
func (m *UpdateGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupReq.Merge(m, src)
}
func (m *UpdateGroupReq) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupReq.Size(m)
}
func (m *UpdateGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupReq proto.InternalMessageInfo

func (m *UpdateGroupReq) GetOperatorId() uint64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func (m *UpdateGroupReq) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *UpdateGroupReq) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *UpdateGroupReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateGroupResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupResp) Reset()         { *m = UpdateGroupResp{} }
func (m *UpdateGroupResp) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupResp) ProtoMessage()    {}
func (*UpdateGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{4}
}

func (m *UpdateGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupResp.Unmarshal(m, b)
}
func (m *UpdateGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupResp.Marshal(b, m, deterministic)
}
func (m *UpdateGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupResp.Merge(m, src)
}
func (m *UpdateGroupResp) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupResp.Size(m)
}
func (m *UpdateGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupResp proto.InternalMessageInfo

type ListGroupsReq struct {
	OperatorId           uint64          `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty,string"`
	Pagereq              *common.PageReq `protobuf:"bytes,2,opt,name=pagereq,proto3" json:"pagereq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListGroupsReq) Reset()         { *m = ListGroupsReq{} }
func (m *ListGroupsReq) String() string { return proto.CompactTextString(m) }
func (*ListGroupsReq) ProtoMessage()    {}
func (*ListGroupsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{5}
}

func (m *ListGroupsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsReq.Unmarshal(m, b)
}
func (m *ListGroupsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsReq.Marshal(b, m, deterministic)
}
func (m *ListGroupsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsReq.Merge(m, src)
}
func (m *ListGroupsReq) XXX_Size() int {
	return xxx_messageInfo_ListGroupsReq.Size(m)
}
func (m *ListGroupsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsReq proto.InternalMessageInfo

func (m *ListGroupsReq) GetOperatorId() uint64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func (m *ListGroupsReq) GetPagereq() *common.PageReq {
	if m != nil {
		return m.Pagereq
	}
	return nil
}

type ListGroupsResp struct {
	Pageresp             *common.PageResp `protobuf:"bytes,1,opt,name=pageresp,proto3" json:"pageresp,omitempty"`
	Groups               []*Group         `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListGroupsResp) Reset()         { *m = ListGroupsResp{} }
func (m *ListGroupsResp) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResp) ProtoMessage()    {}
func (*ListGroupsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{6}
}

func (m *ListGroupsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResp.Unmarshal(m, b)
}
func (m *ListGroupsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResp.Marshal(b, m, deterministic)
}
func (m *ListGroupsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResp.Merge(m, src)
}
func (m *ListGroupsResp) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResp.Size(m)
}
func (m *ListGroupsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResp proto.InternalMessageInfo

func (m *ListGroupsResp) GetPageresp() *common.PageResp {
	if m != nil {
		return m.Pageresp
	}
	return nil
}

func (m *ListGroupsResp) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type GetGroupInfoByNameReq struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	OperatorId           uint64   `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty,string"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupInfoByNameReq) Reset()         { *m = GetGroupInfoByNameReq{} }
func (m *GetGroupInfoByNameReq) String() string { return proto.CompactTextString(m) }
func (*GetGroupInfoByNameReq) ProtoMessage()    {}
func (*GetGroupInfoByNameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{7}
}

func (m *GetGroupInfoByNameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupInfoByNameReq.Unmarshal(m, b)
}
func (m *GetGroupInfoByNameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupInfoByNameReq.Marshal(b, m, deterministic)
}
func (m *GetGroupInfoByNameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupInfoByNameReq.Merge(m, src)
}
func (m *GetGroupInfoByNameReq) XXX_Size() int {
	return xxx_messageInfo_GetGroupInfoByNameReq.Size(m)
}
func (m *GetGroupInfoByNameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupInfoByNameReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupInfoByNameReq proto.InternalMessageInfo

func (m *GetGroupInfoByNameReq) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *GetGroupInfoByNameReq) GetOperatorId() uint64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type GroupIDReq struct {
	Ids                  []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupIDReq) Reset()         { *m = GroupIDReq{} }
func (m *GroupIDReq) String() string { return proto.CompactTextString(m) }
func (*GroupIDReq) ProtoMessage()    {}
func (*GroupIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{8}
}

func (m *GroupIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupIDReq.Unmarshal(m, b)
}
func (m *GroupIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupIDReq.Marshal(b, m, deterministic)
}
func (m *GroupIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupIDReq.Merge(m, src)
}
func (m *GroupIDReq) XXX_Size() int {
	return xxx_messageInfo_GroupIDReq.Size(m)
}
func (m *GroupIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GroupIDReq proto.InternalMessageInfo

func (m *GroupIDReq) GetIds() []uint64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetGroupInfoResp struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupInfoResp) Reset()         { *m = GetGroupInfoResp{} }
func (m *GetGroupInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetGroupInfoResp) ProtoMessage()    {}
func (*GetGroupInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{9}
}

func (m *GetGroupInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupInfoResp.Unmarshal(m, b)
}
func (m *GetGroupInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupInfoResp.Marshal(b, m, deterministic)
}
func (m *GetGroupInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupInfoResp.Merge(m, src)
}
func (m *GetGroupInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetGroupInfoResp.Size(m)
}
func (m *GetGroupInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupInfoResp proto.InternalMessageInfo

func (m *GetGroupInfoResp) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type Group struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Balance              float64  `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt            uint32   `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsBlock              bool     `protobuf:"varint,5,opt,name=is_block,json=isBlock,proto3" json:"is_block,omitempty"`
	OperatorId           uint64   `protobuf:"varint,6,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty,string"`
	Email                string   `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{10}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Group) GetCreatedAt() uint32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Group) GetIsBlock() bool {
	if m != nil {
		return m.IsBlock
	}
	return false
}

func (m *Group) GetOperatorId() uint64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func (m *Group) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AddGroupReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	OperatorId           uint64   `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty,string"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupReq) Reset()         { *m = AddGroupReq{} }
func (m *AddGroupReq) String() string { return proto.CompactTextString(m) }
func (*AddGroupReq) ProtoMessage()    {}
func (*AddGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{11}
}

func (m *AddGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupReq.Unmarshal(m, b)
}
func (m *AddGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupReq.Marshal(b, m, deterministic)
}
func (m *AddGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupReq.Merge(m, src)
}
func (m *AddGroupReq) XXX_Size() int {
	return xxx_messageInfo_AddGroupReq.Size(m)
}
func (m *AddGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupReq proto.InternalMessageInfo

func (m *AddGroupReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddGroupReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddGroupReq) GetOperatorId() uint64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func (m *AddGroupReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AddGroupResp struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupResp) Reset()         { *m = AddGroupResp{} }
func (m *AddGroupResp) String() string { return proto.CompactTextString(m) }
func (*AddGroupResp) ProtoMessage()    {}
func (*AddGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{12}
}

func (m *AddGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupResp.Unmarshal(m, b)
}
func (m *AddGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupResp.Marshal(b, m, deterministic)
}
func (m *AddGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupResp.Merge(m, src)
}
func (m *AddGroupResp) XXX_Size() int {
	return xxx_messageInfo_AddGroupResp.Size(m)
}
func (m *AddGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupResp proto.InternalMessageInfo

func (m *AddGroupResp) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SetGroupStateReq struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`
	Block                bool     `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	OperatorId           uint64   `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty,string"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGroupStateReq) Reset()         { *m = SetGroupStateReq{} }
func (m *SetGroupStateReq) String() string { return proto.CompactTextString(m) }
func (*SetGroupStateReq) ProtoMessage()    {}
func (*SetGroupStateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{13}
}

func (m *SetGroupStateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGroupStateReq.Unmarshal(m, b)
}
func (m *SetGroupStateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGroupStateReq.Marshal(b, m, deterministic)
}
func (m *SetGroupStateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGroupStateReq.Merge(m, src)
}
func (m *SetGroupStateReq) XXX_Size() int {
	return xxx_messageInfo_SetGroupStateReq.Size(m)
}
func (m *SetGroupStateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGroupStateReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetGroupStateReq proto.InternalMessageInfo

func (m *SetGroupStateReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SetGroupStateReq) GetBlock() bool {
	if m != nil {
		return m.Block
	}
	return false
}

func (m *SetGroupStateReq) GetOperatorId() uint64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type SetGroupStateResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGroupStateResp) Reset()         { *m = SetGroupStateResp{} }
func (m *SetGroupStateResp) String() string { return proto.CompactTextString(m) }
func (*SetGroupStateResp) ProtoMessage()    {}
func (*SetGroupStateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{14}
}

func (m *SetGroupStateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGroupStateResp.Unmarshal(m, b)
}
func (m *SetGroupStateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGroupStateResp.Marshal(b, m, deterministic)
}
func (m *SetGroupStateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGroupStateResp.Merge(m, src)
}
func (m *SetGroupStateResp) XXX_Size() int {
	return xxx_messageInfo_SetGroupStateResp.Size(m)
}
func (m *SetGroupStateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGroupStateResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetGroupStateResp proto.InternalMessageInfo

type SetGroupRoyaltyStateReq struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`
	State                bool     `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	OperatorId           uint64   `protobuf:"varint,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty,string"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGroupRoyaltyStateReq) Reset()         { *m = SetGroupRoyaltyStateReq{} }
func (m *SetGroupRoyaltyStateReq) String() string { return proto.CompactTextString(m) }
func (*SetGroupRoyaltyStateReq) ProtoMessage()    {}
func (*SetGroupRoyaltyStateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{15}
}

func (m *SetGroupRoyaltyStateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGroupRoyaltyStateReq.Unmarshal(m, b)
}
func (m *SetGroupRoyaltyStateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGroupRoyaltyStateReq.Marshal(b, m, deterministic)
}
func (m *SetGroupRoyaltyStateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGroupRoyaltyStateReq.Merge(m, src)
}
func (m *SetGroupRoyaltyStateReq) XXX_Size() int {
	return xxx_messageInfo_SetGroupRoyaltyStateReq.Size(m)
}
func (m *SetGroupRoyaltyStateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGroupRoyaltyStateReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetGroupRoyaltyStateReq proto.InternalMessageInfo

func (m *SetGroupRoyaltyStateReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SetGroupRoyaltyStateReq) GetState() bool {
	if m != nil {
		return m.State
	}
	return false
}

func (m *SetGroupRoyaltyStateReq) GetOperatorId() uint64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type SetGroupRoyaltyStateResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGroupRoyaltyStateResp) Reset()         { *m = SetGroupRoyaltyStateResp{} }
func (m *SetGroupRoyaltyStateResp) String() string { return proto.CompactTextString(m) }
func (*SetGroupRoyaltyStateResp) ProtoMessage()    {}
func (*SetGroupRoyaltyStateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{16}
}

func (m *SetGroupRoyaltyStateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGroupRoyaltyStateResp.Unmarshal(m, b)
}
func (m *SetGroupRoyaltyStateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGroupRoyaltyStateResp.Marshal(b, m, deterministic)
}
func (m *SetGroupRoyaltyStateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGroupRoyaltyStateResp.Merge(m, src)
}
func (m *SetGroupRoyaltyStateResp) XXX_Size() int {
	return xxx_messageInfo_SetGroupRoyaltyStateResp.Size(m)
}
func (m *SetGroupRoyaltyStateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGroupRoyaltyStateResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetGroupRoyaltyStateResp proto.InternalMessageInfo

type BindCustomerReq struct {
	GroupId              uint64   `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty,string"`
	CustomerId           uint64   `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty,string"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindCustomerReq) Reset()         { *m = BindCustomerReq{} }
func (m *BindCustomerReq) String() string { return proto.CompactTextString(m) }
func (*BindCustomerReq) ProtoMessage()    {}
func (*BindCustomerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{17}
}

func (m *BindCustomerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindCustomerReq.Unmarshal(m, b)
}
func (m *BindCustomerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindCustomerReq.Marshal(b, m, deterministic)
}
func (m *BindCustomerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindCustomerReq.Merge(m, src)
}
func (m *BindCustomerReq) XXX_Size() int {
	return xxx_messageInfo_BindCustomerReq.Size(m)
}
func (m *BindCustomerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BindCustomerReq.DiscardUnknown(m)
}

var xxx_messageInfo_BindCustomerReq proto.InternalMessageInfo

func (m *BindCustomerReq) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *BindCustomerReq) GetCustomerId() uint64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

type BindCustomerResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindCustomerResp) Reset()         { *m = BindCustomerResp{} }
func (m *BindCustomerResp) String() string { return proto.CompactTextString(m) }
func (*BindCustomerResp) ProtoMessage()    {}
func (*BindCustomerResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{18}
}

func (m *BindCustomerResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindCustomerResp.Unmarshal(m, b)
}
func (m *BindCustomerResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindCustomerResp.Marshal(b, m, deterministic)
}
func (m *BindCustomerResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindCustomerResp.Merge(m, src)
}
func (m *BindCustomerResp) XXX_Size() int {
	return xxx_messageInfo_BindCustomerResp.Size(m)
}
func (m *BindCustomerResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BindCustomerResp.DiscardUnknown(m)
}

var xxx_messageInfo_BindCustomerResp proto.InternalMessageInfo

type ChargeReq struct {
	GroupId              uint64     `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty,string"`
	Amount               float64    `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ChargeMode           ChargeMode `protobuf:"varint,3,opt,name=charge_mode,json=chargeMode,proto3,enum=groupadmin.ChargeMode" json:"charge_mode,omitempty"`
	TransactionBank      string     `protobuf:"bytes,4,opt,name=transaction_bank,json=transactionBank,proto3" json:"transaction_bank,omitempty"`
	TransactionNo        string     `protobuf:"bytes,5,opt,name=transaction_no,json=transactionNo,proto3" json:"transaction_no,omitempty"`
	AdminName            string     `protobuf:"bytes,6,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	Remark               string     `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChargeReq) Reset()         { *m = ChargeReq{} }
func (m *ChargeReq) String() string { return proto.CompactTextString(m) }
func (*ChargeReq) ProtoMessage()    {}
func (*ChargeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{19}
}

func (m *ChargeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeReq.Unmarshal(m, b)
}
func (m *ChargeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeReq.Marshal(b, m, deterministic)
}
func (m *ChargeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeReq.Merge(m, src)
}
func (m *ChargeReq) XXX_Size() int {
	return xxx_messageInfo_ChargeReq.Size(m)
}
func (m *ChargeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeReq proto.InternalMessageInfo

func (m *ChargeReq) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *ChargeReq) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ChargeReq) GetChargeMode() ChargeMode {
	if m != nil {
		return m.ChargeMode
	}
	return ChargeMode_ChargeMode_Unknown
}

func (m *ChargeReq) GetTransactionBank() string {
	if m != nil {
		return m.TransactionBank
	}
	return ""
}

func (m *ChargeReq) GetTransactionNo() string {
	if m != nil {
		return m.TransactionNo
	}
	return ""
}

func (m *ChargeReq) GetAdminName() string {
	if m != nil {
		return m.AdminName
	}
	return ""
}

func (m *ChargeReq) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type ChargeResp struct {
	GroupInfo            *Group   `protobuf:"bytes,1,opt,name=group_info,json=groupInfo,proto3" json:"group_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeResp) Reset()         { *m = ChargeResp{} }
func (m *ChargeResp) String() string { return proto.CompactTextString(m) }
func (*ChargeResp) ProtoMessage()    {}
func (*ChargeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{20}
}

func (m *ChargeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeResp.Unmarshal(m, b)
}
func (m *ChargeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeResp.Marshal(b, m, deterministic)
}
func (m *ChargeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeResp.Merge(m, src)
}
func (m *ChargeResp) XXX_Size() int {
	return xxx_messageInfo_ChargeResp.Size(m)
}
func (m *ChargeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeResp.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeResp proto.InternalMessageInfo

func (m *ChargeResp) GetGroupInfo() *Group {
	if m != nil {
		return m.GroupInfo
	}
	return nil
}

type PayReq struct {
	GroupId              uint64   `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty,string"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	OrderId              uint64   `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty,string"`
	CustomerId           uint64   `protobuf:"varint,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty,string"`
	Source               int32    `protobuf:"varint,5,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayReq) Reset()         { *m = PayReq{} }
func (m *PayReq) String() string { return proto.CompactTextString(m) }
func (*PayReq) ProtoMessage()    {}
func (*PayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{21}
}

func (m *PayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayReq.Unmarshal(m, b)
}
func (m *PayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayReq.Marshal(b, m, deterministic)
}
func (m *PayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayReq.Merge(m, src)
}
func (m *PayReq) XXX_Size() int {
	return xxx_messageInfo_PayReq.Size(m)
}
func (m *PayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayReq proto.InternalMessageInfo

func (m *PayReq) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *PayReq) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PayReq) GetOrderId() uint64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *PayReq) GetCustomerId() uint64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *PayReq) GetSource() int32 {
	if m != nil {
		return m.Source
	}
	return 0
}

type PayResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayResp) Reset()         { *m = PayResp{} }
func (m *PayResp) String() string { return proto.CompactTextString(m) }
func (*PayResp) ProtoMessage()    {}
func (*PayResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{22}
}

func (m *PayResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayResp.Unmarshal(m, b)
}
func (m *PayResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayResp.Marshal(b, m, deterministic)
}
func (m *PayResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayResp.Merge(m, src)
}
func (m *PayResp) XXX_Size() int {
	return xxx_messageInfo_PayResp.Size(m)
}
func (m *PayResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayResp.DiscardUnknown(m)
}

var xxx_messageInfo_PayResp proto.InternalMessageInfo

type RefundReq struct {
	GroupId              uint64   `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty,string"`
	OrderId              uint64   `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty,string"`
	Amount               float64  `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefundReq) Reset()         { *m = RefundReq{} }
func (m *RefundReq) String() string { return proto.CompactTextString(m) }
func (*RefundReq) ProtoMessage()    {}
func (*RefundReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{23}
}

func (m *RefundReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundReq.Unmarshal(m, b)
}
func (m *RefundReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundReq.Marshal(b, m, deterministic)
}
func (m *RefundReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundReq.Merge(m, src)
}
func (m *RefundReq) XXX_Size() int {
	return xxx_messageInfo_RefundReq.Size(m)
}
func (m *RefundReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefundReq proto.InternalMessageInfo

func (m *RefundReq) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *RefundReq) GetOrderId() uint64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *RefundReq) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type RefundResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefundResp) Reset()         { *m = RefundResp{} }
func (m *RefundResp) String() string { return proto.CompactTextString(m) }
func (*RefundResp) ProtoMessage()    {}
func (*RefundResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{24}
}

func (m *RefundResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundResp.Unmarshal(m, b)
}
func (m *RefundResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundResp.Marshal(b, m, deterministic)
}
func (m *RefundResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundResp.Merge(m, src)
}
func (m *RefundResp) XXX_Size() int {
	return xxx_messageInfo_RefundResp.Size(m)
}
func (m *RefundResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundResp.DiscardUnknown(m)
}

var xxx_messageInfo_RefundResp proto.InternalMessageInfo

// 流水
type Transaction struct {
	TransactionId        uint64     `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty,string"`
	GroupId              uint64     `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty,string"`
	GroupName            string     `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Amount               float64    `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance              float64    `protobuf:"fixed64,5,opt,name=balance,proto3" json:"balance,omitempty"`
	ChargeMode           ChargeMode `protobuf:"varint,6,opt,name=charge_mode,json=chargeMode,proto3,enum=groupadmin.ChargeMode" json:"charge_mode,omitempty"`
	TransactionBank      string     `protobuf:"bytes,7,opt,name=transaction_bank,json=transactionBank,proto3" json:"transaction_bank,omitempty"`
	TransactionNo        string     `protobuf:"bytes,8,opt,name=transaction_no,json=transactionNo,proto3" json:"transaction_no,omitempty"`
	AdminName            string     `protobuf:"bytes,9,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	Remark               string     `protobuf:"bytes,12,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt            int32      `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{25}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTransactionId() uint64 {
	if m != nil {
		return m.TransactionId
	}
	return 0
}

func (m *Transaction) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *Transaction) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Transaction) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Transaction) GetChargeMode() ChargeMode {
	if m != nil {
		return m.ChargeMode
	}
	return ChargeMode_ChargeMode_Unknown
}

func (m *Transaction) GetTransactionBank() string {
	if m != nil {
		return m.TransactionBank
	}
	return ""
}

func (m *Transaction) GetTransactionNo() string {
	if m != nil {
		return m.TransactionNo
	}
	return ""
}

func (m *Transaction) GetAdminName() string {
	if m != nil {
		return m.AdminName
	}
	return ""
}

func (m *Transaction) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *Transaction) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type GetTransactionsByGroupReq struct {
	GroupId              uint64          `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty,string"`
	Pagereq              *common.PageReq `protobuf:"bytes,2,opt,name=pagereq,proto3" json:"pagereq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTransactionsByGroupReq) Reset()         { *m = GetTransactionsByGroupReq{} }
func (m *GetTransactionsByGroupReq) String() string { return proto.CompactTextString(m) }
func (*GetTransactionsByGroupReq) ProtoMessage()    {}
func (*GetTransactionsByGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{26}
}

func (m *GetTransactionsByGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionsByGroupReq.Unmarshal(m, b)
}
func (m *GetTransactionsByGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionsByGroupReq.Marshal(b, m, deterministic)
}
func (m *GetTransactionsByGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionsByGroupReq.Merge(m, src)
}
func (m *GetTransactionsByGroupReq) XXX_Size() int {
	return xxx_messageInfo_GetTransactionsByGroupReq.Size(m)
}
func (m *GetTransactionsByGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionsByGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionsByGroupReq proto.InternalMessageInfo

func (m *GetTransactionsByGroupReq) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GetTransactionsByGroupReq) GetPagereq() *common.PageReq {
	if m != nil {
		return m.Pagereq
	}
	return nil
}

type GetTransactionsByGroupResp struct {
	Pageresp             *common.PageResp `protobuf:"bytes,1,opt,name=pageresp,proto3" json:"pageresp,omitempty"`
	Transactions         []*Transaction   `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetTransactionsByGroupResp) Reset()         { *m = GetTransactionsByGroupResp{} }
func (m *GetTransactionsByGroupResp) String() string { return proto.CompactTextString(m) }
func (*GetTransactionsByGroupResp) ProtoMessage()    {}
func (*GetTransactionsByGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{27}
}

func (m *GetTransactionsByGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionsByGroupResp.Unmarshal(m, b)
}
func (m *GetTransactionsByGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionsByGroupResp.Marshal(b, m, deterministic)
}
func (m *GetTransactionsByGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionsByGroupResp.Merge(m, src)
}
func (m *GetTransactionsByGroupResp) XXX_Size() int {
	return xxx_messageInfo_GetTransactionsByGroupResp.Size(m)
}
func (m *GetTransactionsByGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionsByGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionsByGroupResp proto.InternalMessageInfo

func (m *GetTransactionsByGroupResp) GetPageresp() *common.PageResp {
	if m != nil {
		return m.Pageresp
	}
	return nil
}

func (m *GetTransactionsByGroupResp) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type GetTransactionByIDReq struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty,string"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionByIDReq) Reset()         { *m = GetTransactionByIDReq{} }
func (m *GetTransactionByIDReq) String() string { return proto.CompactTextString(m) }
func (*GetTransactionByIDReq) ProtoMessage()    {}
func (*GetTransactionByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{28}
}

func (m *GetTransactionByIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionByIDReq.Unmarshal(m, b)
}
func (m *GetTransactionByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionByIDReq.Marshal(b, m, deterministic)
}
func (m *GetTransactionByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionByIDReq.Merge(m, src)
}
func (m *GetTransactionByIDReq) XXX_Size() int {
	return xxx_messageInfo_GetTransactionByIDReq.Size(m)
}
func (m *GetTransactionByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionByIDReq proto.InternalMessageInfo

func (m *GetTransactionByIDReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ChangeTransactionChargeModeReq struct {
	TransactionId        uint64     `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty,string"`
	ChargeMode           ChargeMode `protobuf:"varint,2,opt,name=charge_mode,json=chargeMode,proto3,enum=groupadmin.ChargeMode" json:"charge_mode,omitempty"`
	TransactionBank      string     `protobuf:"bytes,3,opt,name=transaction_bank,json=transactionBank,proto3" json:"transaction_bank,omitempty"`
	TransactionNo        string     `protobuf:"bytes,4,opt,name=transaction_no,json=transactionNo,proto3" json:"transaction_no,omitempty"`
	AdminName            string     `protobuf:"bytes,5,opt,name=admin_name,json=adminName,proto3" json:"admin_name,omitempty"`
	Remark               string     `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ChangeTransactionChargeModeReq) Reset()         { *m = ChangeTransactionChargeModeReq{} }
func (m *ChangeTransactionChargeModeReq) String() string { return proto.CompactTextString(m) }
func (*ChangeTransactionChargeModeReq) ProtoMessage()    {}
func (*ChangeTransactionChargeModeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59652f4522bd8366, []int{29}
}

func (m *ChangeTransactionChargeModeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeTransactionChargeModeReq.Unmarshal(m, b)
}
func (m *ChangeTransactionChargeModeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeTransactionChargeModeReq.Marshal(b, m, deterministic)
}
func (m *ChangeTransactionChargeModeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeTransactionChargeModeReq.Merge(m, src)
}
func (m *ChangeTransactionChargeModeReq) XXX_Size() int {
	return xxx_messageInfo_ChangeTransactionChargeModeReq.Size(m)
}
func (m *ChangeTransactionChargeModeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeTransactionChargeModeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeTransactionChargeModeReq proto.InternalMessageInfo

func (m *ChangeTransactionChargeModeReq) GetTransactionId() uint64 {
	if m != nil {
		return m.TransactionId
	}
	return 0
}

func (m *ChangeTransactionChargeModeReq) GetChargeMode() ChargeMode {
	if m != nil {
		return m.ChargeMode
	}
	return ChargeMode_ChargeMode_Unknown
}

func (m *ChangeTransactionChargeModeReq) GetTransactionBank() string {
	if m != nil {
		return m.TransactionBank
	}
	return ""
}

func (m *ChangeTransactionChargeModeReq) GetTransactionNo() string {
	if m != nil {
		return m.TransactionNo
	}
	return ""
}

func (m *ChangeTransactionChargeModeReq) GetAdminName() string {
	if m != nil {
		return m.AdminName
	}
	return ""
}

func (m *ChangeTransactionChargeModeReq) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func init() {
	proto.RegisterEnum("groupadmin.GroupState", GroupState_name, GroupState_value)
	proto.RegisterEnum("groupadmin.ChargeMode", ChargeMode_name, ChargeMode_value)
	proto.RegisterType((*GroupMember)(nil), "groupadmin.GroupMember")
	proto.RegisterType((*GetMemberInfoByCustomerReq)(nil), "groupadmin.GetMemberInfoByCustomerReq")
	proto.RegisterType((*GetMemberInfoByCustomerResp)(nil), "groupadmin.GetMemberInfoByCustomerResp")
	proto.RegisterType((*UpdateGroupReq)(nil), "groupadmin.UpdateGroupReq")
	proto.RegisterType((*UpdateGroupResp)(nil), "groupadmin.UpdateGroupResp")
	proto.RegisterType((*ListGroupsReq)(nil), "groupadmin.ListGroupsReq")
	proto.RegisterType((*ListGroupsResp)(nil), "groupadmin.ListGroupsResp")
	proto.RegisterType((*GetGroupInfoByNameReq)(nil), "groupadmin.GetGroupInfoByNameReq")
	proto.RegisterType((*GroupIDReq)(nil), "groupadmin.GroupIDReq")
	proto.RegisterType((*GetGroupInfoResp)(nil), "groupadmin.GetGroupInfoResp")
	proto.RegisterType((*Group)(nil), "groupadmin.Group")
	proto.RegisterType((*AddGroupReq)(nil), "groupadmin.AddGroupReq")
	proto.RegisterType((*AddGroupResp)(nil), "groupadmin.AddGroupResp")
	proto.RegisterType((*SetGroupStateReq)(nil), "groupadmin.SetGroupStateReq")
	proto.RegisterType((*SetGroupStateResp)(nil), "groupadmin.SetGroupStateResp")
	proto.RegisterType((*SetGroupRoyaltyStateReq)(nil), "groupadmin.SetGroupRoyaltyStateReq")
	proto.RegisterType((*SetGroupRoyaltyStateResp)(nil), "groupadmin.SetGroupRoyaltyStateResp")
	proto.RegisterType((*BindCustomerReq)(nil), "groupadmin.BindCustomerReq")
	proto.RegisterType((*BindCustomerResp)(nil), "groupadmin.BindCustomerResp")
	proto.RegisterType((*ChargeReq)(nil), "groupadmin.ChargeReq")
	proto.RegisterType((*ChargeResp)(nil), "groupadmin.ChargeResp")
	proto.RegisterType((*PayReq)(nil), "groupadmin.PayReq")
	proto.RegisterType((*PayResp)(nil), "groupadmin.PayResp")
	proto.RegisterType((*RefundReq)(nil), "groupadmin.RefundReq")
	proto.RegisterType((*RefundResp)(nil), "groupadmin.RefundResp")
	proto.RegisterType((*Transaction)(nil), "groupadmin.Transaction")
	proto.RegisterType((*GetTransactionsByGroupReq)(nil), "groupadmin.GetTransactionsByGroupReq")
	proto.RegisterType((*GetTransactionsByGroupResp)(nil), "groupadmin.GetTransactionsByGroupResp")
	proto.RegisterType((*GetTransactionByIDReq)(nil), "groupadmin.GetTransactionByIDReq")
	proto.RegisterType((*ChangeTransactionChargeModeReq)(nil), "groupadmin.ChangeTransactionChargeModeReq")
}

func init() { proto.RegisterFile("group-admin.proto", fileDescriptor_59652f4522bd8366) }

var fileDescriptor_59652f4522bd8366 = []byte{
	// 1339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x0e, 0x29, 0x89, 0x92, 0x46, 0xfe, 0xa0, 0x37, 0x89, 0x22, 0x33, 0x6f, 0xf2, 0xba, 0x4c,
	0x93, 0x38, 0x41, 0x23, 0x17, 0x2e, 0x8a, 0xb4, 0x28, 0x52, 0x20, 0x72, 0x50, 0xd7, 0x40, 0x12,
	0x18, 0x74, 0x83, 0x20, 0x2d, 0x50, 0x75, 0x25, 0x6e, 0x14, 0xd6, 0x22, 0x77, 0xcd, 0xa5, 0x6b,
	0xe8, 0xd6, 0x9e, 0x8a, 0x9e, 0x7a, 0xe9, 0x6f, 0xe9, 0x9f, 0xe9, 0x9f, 0x29, 0x38, 0x24, 0xa5,
	0x25, 0xa9, 0x0f, 0xa7, 0xb9, 0x71, 0x67, 0x76, 0x67, 0x9e, 0x9d, 0x79, 0x76, 0x66, 0x24, 0xd8,
	0x1a, 0x85, 0xfc, 0x5c, 0x3c, 0xa2, 0xae, 0xef, 0x05, 0x5d, 0x11, 0xf2, 0x88, 0x13, 0x40, 0x11,
	0x4a, 0xac, 0xb5, 0x21, 0xf7, 0x7d, 0x9e, 0x6a, 0xec, 0xbf, 0x34, 0x68, 0x1d, 0xc6, 0xca, 0x17,
	0xcc, 0x1f, 0xb0, 0x90, 0x6c, 0x80, 0xee, 0xb9, 0x1d, 0x6d, 0x47, 0xdb, 0xad, 0x3a, 0xba, 0xe7,
	0x92, 0xff, 0x43, 0x6b, 0x78, 0x2e, 0x23, 0xee, 0xb3, 0xb0, 0xef, 0xb9, 0x1d, 0x1d, 0x15, 0x90,
	0x89, 0x8e, 0x5c, 0xb2, 0x0d, 0x0d, 0x34, 0x1e, 0x6b, 0x2b, 0xa8, 0xad, 0xe3, 0xfa, 0x08, 0xcf,
	0x72, 0xc1, 0x42, 0x1a, 0x71, 0x3c, 0x5b, 0x4d, 0xce, 0x66, 0xa2, 0x23, 0x97, 0x74, 0xa0, 0x7e,
	0x24, 0x7b, 0x63, 0x3e, 0x3c, 0xed, 0xd4, 0x76, 0xb4, 0xdd, 0x86, 0x93, 0x2d, 0xed, 0x1f, 0xc1,
	0x3a, 0x64, 0x51, 0x82, 0xe9, 0x28, 0x78, 0xcb, 0x7b, 0x93, 0x83, 0xd4, 0xa5, 0xc3, 0xce, 0x8a,
	0xa0, 0xb4, 0x12, 0xa8, 0x82, 0x67, 0xbd, 0xe8, 0xd9, 0x7e, 0x0d, 0x37, 0x17, 0xda, 0x97, 0x82,
	0x7c, 0x01, 0x2d, 0x1f, 0x75, 0x7d, 0x2f, 0x78, 0xcb, 0xd1, 0x41, 0x6b, 0xff, 0x46, 0x77, 0x16,
	0xc5, 0xae, 0x12, 0x33, 0x07, 0xfc, 0xa9, 0x1d, 0x3b, 0x82, 0x8d, 0x57, 0xc2, 0xa5, 0x11, 0xc3,
	0x0d, 0x29, 0x58, 0x15, 0x8b, 0x56, 0x8a, 0x82, 0x1a, 0x41, 0x3d, 0x1f, 0x41, 0x13, 0x2a, 0xe2,
	0x22, 0x89, 0x6b, 0xd3, 0x89, 0x3f, 0xc9, 0x35, 0xa8, 0x31, 0x9f, 0x7a, 0x63, 0x8c, 0x66, 0xd3,
	0x49, 0x16, 0xf6, 0x16, 0x6c, 0xe6, 0xbc, 0x4a, 0x61, 0xff, 0x00, 0xeb, 0xcf, 0x3d, 0x19, 0xa1,
	0x40, 0x5e, 0x0a, 0xc7, 0x03, 0xa8, 0x0b, 0x3a, 0x62, 0x21, 0x3b, 0x43, 0x18, 0xad, 0xfd, 0xcd,
	0x6e, 0x4a, 0x95, 0x63, 0x3a, 0x62, 0x0e, 0x3b, 0x73, 0x32, 0xbd, 0xed, 0xc1, 0x86, 0x6a, 0x5c,
	0x0a, 0xf2, 0x09, 0x34, 0x12, 0xa5, 0x14, 0x69, 0xb8, 0xcc, 0xfc, 0x69, 0x29, 0x9c, 0xe9, 0x0e,
	0xf2, 0x00, 0x0c, 0xbc, 0xa2, 0xec, 0xe8, 0x3b, 0x95, 0xdd, 0xd6, 0xfe, 0x56, 0x29, 0xb4, 0x4e,
	0xba, 0xc1, 0x7e, 0x0d, 0xd7, 0x0f, 0x59, 0xe2, 0x29, 0x49, 0xd4, 0x4b, 0xea, 0xc7, 0x60, 0xc8,
	0x2d, 0x48, 0x58, 0xdd, 0x0f, 0xa8, 0xcf, 0xd0, 0x67, 0xd3, 0x69, 0xa2, 0x24, 0xde, 0xb1, 0x9a,
	0x02, 0xb7, 0x01, 0x12, 0xab, 0xcf, 0x62, 0x6b, 0x26, 0x54, 0x3c, 0x57, 0x76, 0xb4, 0x9d, 0xca,
	0x6e, 0xd5, 0x89, 0x3f, 0xed, 0x27, 0x60, 0xaa, 0x8e, 0x9d, 0x3c, 0x6e, 0x6d, 0x15, 0xee, 0xbf,
	0x35, 0xa8, 0xa1, 0xa4, 0xf4, 0xa4, 0x08, 0x54, 0x11, 0xb2, 0x8e, 0x90, 0xf1, 0x3b, 0x7e, 0x09,
	0x03, 0x3a, 0xa6, 0xc1, 0x90, 0x61, 0xb2, 0x35, 0x27, 0x5b, 0xc6, 0xd7, 0x1c, 0x86, 0x8c, 0x46,
	0xcc, 0xed, 0xd3, 0x08, 0xb3, 0xbe, 0xee, 0x34, 0x53, 0xc9, 0xd3, 0x28, 0x26, 0x8f, 0x27, 0xfb,
	0x03, 0xf5, 0x0d, 0x79, 0xc9, 0x1b, 0x2a, 0x46, 0xc0, 0x28, 0x25, 0x7c, 0xca, 0xa5, 0xba, 0xca,
	0xa5, 0x08, 0x5a, 0x4f, 0x5d, 0x77, 0x4a, 0xdf, 0x0c, 0xad, 0xa6, 0xa0, 0xb5, 0xe2, 0x64, 0x4b,
	0x79, 0xc1, 0x43, 0x37, 0xbd, 0xc5, 0x74, 0x5d, 0xf4, 0x5a, 0x59, 0xec, 0x35, 0xc7, 0xe0, 0xdb,
	0xb0, 0x36, 0xf3, 0x2a, 0x4b, 0x41, 0xb3, 0xdf, 0x80, 0x79, 0x92, 0x66, 0xe3, 0x24, 0xa2, 0x11,
	0x32, 0xa0, 0x18, 0xd8, 0x6b, 0x50, 0x4b, 0x02, 0xa1, 0x63, 0x20, 0x92, 0xc5, 0x4a, 0x40, 0xf6,
	0x55, 0xd8, 0x2a, 0x98, 0x96, 0xc2, 0xfe, 0x09, 0x6e, 0x64, 0x42, 0x87, 0x4f, 0xe8, 0x38, 0x9a,
	0x2c, 0x73, 0x2b, 0x63, 0x5d, 0xe6, 0x16, 0x17, 0xab, 0xdd, 0x5a, 0xd0, 0x99, 0xef, 0x41, 0x0a,
	0xfb, 0x05, 0x6c, 0xf6, 0xbc, 0xc0, 0x55, 0x6b, 0x9e, 0x5a, 0x25, 0xb4, 0x52, 0x9d, 0x5d, 0x5a,
	0xa3, 0x6d, 0x02, 0x66, 0xde, 0x9c, 0x14, 0xf6, 0xaf, 0x3a, 0x34, 0x0f, 0xde, 0xd1, 0x10, 0x5f,
	0xf6, 0x32, 0xeb, 0x6d, 0x30, 0xa8, 0xcf, 0xcf, 0x83, 0x08, 0x0d, 0x6b, 0x4e, 0xba, 0x22, 0x8f,
	0xa1, 0x35, 0xc4, 0xf3, 0x7d, 0x9f, 0xbb, 0x09, 0x6d, 0x37, 0xf6, 0xdb, 0xea, 0x83, 0x48, 0xcc,
	0xbf, 0xe0, 0x2e, 0x73, 0x60, 0x38, 0xfd, 0x26, 0x0f, 0xc0, 0x8c, 0x42, 0x1a, 0x48, 0x3a, 0x8c,
	0x3c, 0x1e, 0xf4, 0x07, 0x34, 0x38, 0x4d, 0xb9, 0xb0, 0xa9, 0xc8, 0x7b, 0x34, 0x38, 0x25, 0x77,
	0x61, 0x43, 0xdd, 0x1a, 0x70, 0xe4, 0x78, 0xd3, 0x59, 0x57, 0xa4, 0x2f, 0x79, 0xfc, 0x46, 0xd0,
	0x63, 0x52, 0x0a, 0x8c, 0xa4, 0x14, 0xa0, 0x04, 0x4b, 0x41, 0x1b, 0x8c, 0x90, 0xf9, 0x34, 0x3c,
	0x4d, 0x89, 0x9e, 0xae, 0xec, 0xaf, 0x01, 0xb2, 0x08, 0x48, 0x41, 0x3e, 0xcd, 0xea, 0x89, 0x52,
	0xf2, 0xe7, 0xbc, 0xef, 0xa4, 0xc4, 0x60, 0xad, 0xff, 0x53, 0x03, 0xe3, 0x98, 0x4e, 0xfe, 0x63,
	0xfc, 0xb6, 0xa1, 0xc1, 0x43, 0x97, 0x29, 0xec, 0xa8, 0xe3, 0xba, 0x9c, 0xd0, 0x6a, 0xa9, 0xbf,
	0xb5, 0xc1, 0x90, 0xfc, 0x3c, 0x1c, 0x32, 0x8c, 0x47, 0xcd, 0x49, 0x57, 0x76, 0x13, 0xea, 0x08,
	0x48, 0x0a, 0xfb, 0x0d, 0x34, 0x1d, 0xf6, 0xf6, 0x3c, 0x70, 0x57, 0xc0, 0x53, 0x61, 0xe8, 0x79,
	0x18, 0x33, 0xe4, 0x15, 0x15, 0xb9, 0xbd, 0x06, 0x90, 0x99, 0x96, 0xc2, 0xfe, 0xad, 0x02, 0xad,
	0xef, 0x66, 0xe9, 0x28, 0xe6, 0x6c, 0xea, 0x51, 0xcd, 0xd9, 0xf2, 0xae, 0x97, 0xaf, 0xec, 0x95,
	0x62, 0x65, 0x9f, 0xc1, 0xaa, 0xe6, 0x02, 0xaa, 0xd4, 0xd0, 0x5a, 0xbe, 0x86, 0x16, 0xa8, 0x6a,
	0x7c, 0x10, 0x55, 0xeb, 0x97, 0xa5, 0x6a, 0x63, 0x35, 0x55, 0x9b, 0x8b, 0xa9, 0xba, 0xa6, 0x52,
	0xb5, 0xd0, 0x05, 0xd6, 0x31, 0xe9, 0xb3, 0x2e, 0x60, 0x53, 0xd8, 0x3e, 0x64, 0x91, 0x92, 0x05,
	0xd9, 0x9b, 0x4c, 0x2b, 0xf8, 0x92, 0xe4, 0xbf, 0x47, 0xcb, 0xff, 0x5d, 0xc3, 0x91, 0x6c, 0xae,
	0x8f, 0xf7, 0xee, 0xff, 0x5f, 0xc1, 0x9a, 0x12, 0x96, 0x6c, 0x0a, 0xc8, 0x0d, 0x58, 0x8a, 0x23,
	0x27, 0xb7, 0xd9, 0xbe, 0x8f, 0x13, 0x81, 0xa2, 0xef, 0x4d, 0x92, 0x1e, 0x5e, 0xec, 0x19, 0x7f,
	0xe8, 0x70, 0xfb, 0xe0, 0x1d, 0x0d, 0x46, 0x4c, 0xd9, 0xac, 0x64, 0x9a, 0x9d, 0x5d, 0x96, 0xac,
	0x05, 0x02, 0xe9, 0x1f, 0x44, 0xa0, 0xca, 0x65, 0x09, 0x54, 0x5d, 0x4d, 0xa0, 0xda, 0x62, 0x02,
	0x19, 0x2a, 0x81, 0x1e, 0xde, 0x49, 0xa7, 0x1d, 0xec, 0x31, 0x04, 0xc0, 0x78, 0xc9, 0x43, 0x9f,
	0x8e, 0xcd, 0x2b, 0xa4, 0x09, 0x35, 0x9c, 0x17, 0x4c, 0xed, 0xe1, 0x71, 0x56, 0x10, 0x11, 0x7b,
	0x1b, 0xc8, 0x6c, 0xd5, 0x7f, 0x15, 0x9c, 0x06, 0xfc, 0x22, 0x30, 0xaf, 0x90, 0xab, 0xb0, 0xa9,
	0xc8, 0x63, 0xec, 0xa6, 0x46, 0xae, 0xc3, 0x96, 0x22, 0x3c, 0x99, 0xc8, 0x88, 0xf9, 0xa6, 0xbe,
	0xff, 0x4f, 0x03, 0x08, 0xfa, 0x7d, 0x1a, 0x23, 0x3c, 0x61, 0xe1, 0x2f, 0xde, 0x90, 0x49, 0x72,
	0x00, 0x30, 0x9b, 0x1f, 0xc9, 0xb6, 0x1a, 0xc8, 0xdc, 0xd0, 0x6a, 0x59, 0x8b, 0x54, 0x52, 0x90,
	0x27, 0xd0, 0xc8, 0x46, 0x06, 0x92, 0xa3, 0x8e, 0x32, 0xbe, 0x58, 0x9d, 0xf9, 0x0a, 0x29, 0xc8,
	0x37, 0xd0, 0x52, 0x66, 0x66, 0x92, 0xf3, 0x94, 0x1f, 0xe1, 0xad, 0x9b, 0x0b, 0x75, 0x52, 0x90,
	0xe7, 0xb0, 0x9e, 0x1b, 0x1f, 0xc8, 0xff, 0xd4, 0xdd, 0xc5, 0xa1, 0xc5, 0xba, 0xb5, 0x44, 0x2b,
	0x05, 0xa1, 0x70, 0x6d, 0xde, 0x54, 0x40, 0xee, 0xcc, 0x3b, 0x56, 0x98, 0x4c, 0xac, 0x8f, 0x57,
	0x6f, 0x92, 0x82, 0x3c, 0x83, 0x35, 0x75, 0xb0, 0x25, 0xed, 0x52, 0x93, 0xc3, 0xe7, 0x64, 0xe5,
	0xee, 0x51, 0x1a, 0x85, 0x5f, 0x01, 0x29, 0xcf, 0xe5, 0xe4, 0xa3, 0x45, 0x67, 0xa6, 0x73, 0xfb,
	0x0a, 0xb3, 0x3f, 0xc3, 0x8d, 0x05, 0x3f, 0xcc, 0xc8, 0xbd, 0xc2, 0xc1, 0x05, 0xbf, 0x0e, 0xad,
	0xfb, 0x97, 0xda, 0x27, 0x05, 0x79, 0x0c, 0x46, 0xc2, 0x59, 0x72, 0xbd, 0xfc, 0x94, 0x63, 0x4b,
	0xed, 0x79, 0x62, 0x29, 0x48, 0x17, 0x2a, 0xc7, 0x74, 0x42, 0x88, 0xaa, 0x4e, 0x06, 0x01, 0xeb,
	0x6a, 0x49, 0x96, 0x38, 0x4a, 0x1a, 0x66, 0xde, 0xd1, 0xb4, 0x3f, 0xe7, 0x1d, 0xcd, 0x7a, 0x2b,
	0x19, 0x41, 0x7b, 0x7e, 0xcd, 0x25, 0x77, 0x0b, 0x97, 0x9c, 0x5f, 0xfb, 0xad, 0x7b, 0x97, 0xd9,
	0x26, 0x05, 0x39, 0xc6, 0x6c, 0x16, 0x6a, 0x6a, 0x29, 0x9b, 0xe5, 0x9a, 0x6b, 0x2d, 0xaa, 0xd9,
	0x64, 0x00, 0x37, 0x97, 0xd4, 0x5e, 0xf2, 0xb0, 0x10, 0xda, 0x25, 0x45, 0x7a, 0xa1, 0x8f, 0xde,
	0x97, 0xdf, 0x56, 0xbe, 0xff, 0x7c, 0xe4, 0x45, 0x63, 0x3a, 0xe8, 0x8e, 0xb8, 0xc7, 0xa3, 0x6e,
	0xc0, 0xa2, 0x3d, 0xe9, 0xb2, 0x47, 0x03, 0x2a, 0xd9, 0x1e, 0xfe, 0xc3, 0x31, 0xe4, 0xe3, 0xbd,
	0x11, 0x1f, 0xd3, 0x60, 0xb4, 0xa7, 0xfc, 0x2f, 0x32, 0x30, 0x50, 0xf9, 0xd9, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xd4, 0x11, 0xd7, 0x59, 0x2d, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GroupAdminServicesClient is the client API for GroupAdminServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GroupAdminServicesClient interface {
	//获取客户列表
	ListGroups(ctx context.Context, in *ListGroupsReq, opts ...grpc.CallOption) (*ListGroupsResp, error)
	//添加集团
	AddGroup(ctx context.Context, in *AddGroupReq, opts ...grpc.CallOption) (*AddGroupResp, error)
	//更改集团密码
	UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupResp, error)
	//设置集团状态
	SetGroupState(ctx context.Context, in *SetGroupStateReq, opts ...grpc.CallOption) (*SetGroupStateResp, error)
	// 设置分润状态
	SetGroupRoyaltyState(ctx context.Context, in *SetGroupRoyaltyStateReq, opts ...grpc.CallOption) (*SetGroupRoyaltyStateResp, error)
	//获取集团信息
	GetGroupInfo(ctx context.Context, in *GroupIDReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error)
	// 根据名称获取集团信息
	GetGroupInfoByName(ctx context.Context, in *GetGroupInfoByNameReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error)
	// 根据用户获取集团成员信息
	GetMemberInfoByCustomer(ctx context.Context, in *GetMemberInfoByCustomerReq, opts ...grpc.CallOption) (*GetMemberInfoByCustomerResp, error)
	//充值
	Charge(ctx context.Context, in *ChargeReq, opts ...grpc.CallOption) (*ChargeResp, error)
	// 支付和退款走队列处理
	Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error)
	Refund(ctx context.Context, in *RefundReq, opts ...grpc.CallOption) (*RefundResp, error)
	// 获取集团所有充值记录
	GetTransactionsByGroup(ctx context.Context, in *GetTransactionsByGroupReq, opts ...grpc.CallOption) (*GetTransactionsByGroupResp, error)
	// 根据id获取一条充值记录
	GetTransactionByID(ctx context.Context, in *GetTransactionByIDReq, opts ...grpc.CallOption) (*Transaction, error)
	// 变更流水信息
	ChangeTransactionChargeMode(ctx context.Context, in *ChangeTransactionChargeModeReq, opts ...grpc.CallOption) (*Transaction, error)
}

type groupAdminServicesClient struct {
	cc *grpc.ClientConn
}

func NewGroupAdminServicesClient(cc *grpc.ClientConn) GroupAdminServicesClient {
	return &groupAdminServicesClient{cc}
}

func (c *groupAdminServicesClient) ListGroups(ctx context.Context, in *ListGroupsReq, opts ...grpc.CallOption) (*ListGroupsResp, error) {
	out := new(ListGroupsResp)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/ListGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupAdminServicesClient) AddGroup(ctx context.Context, in *AddGroupReq, opts ...grpc.CallOption) (*AddGroupResp, error) {
	out := new(AddGroupResp)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/AddGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupAdminServicesClient) UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupResp, error) {
	out := new(UpdateGroupResp)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/UpdateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupAdminServicesClient) SetGroupState(ctx context.Context, in *SetGroupStateReq, opts ...grpc.CallOption) (*SetGroupStateResp, error) {
	out := new(SetGroupStateResp)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/SetGroupState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupAdminServicesClient) SetGroupRoyaltyState(ctx context.Context, in *SetGroupRoyaltyStateReq, opts ...grpc.CallOption) (*SetGroupRoyaltyStateResp, error) {
	out := new(SetGroupRoyaltyStateResp)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/SetGroupRoyaltyState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupAdminServicesClient) GetGroupInfo(ctx context.Context, in *GroupIDReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error) {
	out := new(GetGroupInfoResp)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/GetGroupInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupAdminServicesClient) GetGroupInfoByName(ctx context.Context, in *GetGroupInfoByNameReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error) {
	out := new(GetGroupInfoResp)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/GetGroupInfoByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupAdminServicesClient) GetMemberInfoByCustomer(ctx context.Context, in *GetMemberInfoByCustomerReq, opts ...grpc.CallOption) (*GetMemberInfoByCustomerResp, error) {
	out := new(GetMemberInfoByCustomerResp)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/GetMemberInfoByCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupAdminServicesClient) Charge(ctx context.Context, in *ChargeReq, opts ...grpc.CallOption) (*ChargeResp, error) {
	out := new(ChargeResp)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/Charge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupAdminServicesClient) Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error) {
	out := new(PayResp)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/Pay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupAdminServicesClient) Refund(ctx context.Context, in *RefundReq, opts ...grpc.CallOption) (*RefundResp, error) {
	out := new(RefundResp)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/Refund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupAdminServicesClient) GetTransactionsByGroup(ctx context.Context, in *GetTransactionsByGroupReq, opts ...grpc.CallOption) (*GetTransactionsByGroupResp, error) {
	out := new(GetTransactionsByGroupResp)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/GetTransactionsByGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupAdminServicesClient) GetTransactionByID(ctx context.Context, in *GetTransactionByIDReq, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/GetTransactionByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupAdminServicesClient) ChangeTransactionChargeMode(ctx context.Context, in *ChangeTransactionChargeModeReq, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/groupadmin.GroupAdminServices/ChangeTransactionChargeMode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupAdminServicesServer is the server API for GroupAdminServices service.
type GroupAdminServicesServer interface {
	//获取客户列表
	ListGroups(context.Context, *ListGroupsReq) (*ListGroupsResp, error)
	//添加集团
	AddGroup(context.Context, *AddGroupReq) (*AddGroupResp, error)
	//更改集团密码
	UpdateGroup(context.Context, *UpdateGroupReq) (*UpdateGroupResp, error)
	//设置集团状态
	SetGroupState(context.Context, *SetGroupStateReq) (*SetGroupStateResp, error)
	// 设置分润状态
	SetGroupRoyaltyState(context.Context, *SetGroupRoyaltyStateReq) (*SetGroupRoyaltyStateResp, error)
	//获取集团信息
	GetGroupInfo(context.Context, *GroupIDReq) (*GetGroupInfoResp, error)
	// 根据名称获取集团信息
	GetGroupInfoByName(context.Context, *GetGroupInfoByNameReq) (*GetGroupInfoResp, error)
	// 根据用户获取集团成员信息
	GetMemberInfoByCustomer(context.Context, *GetMemberInfoByCustomerReq) (*GetMemberInfoByCustomerResp, error)
	//充值
	Charge(context.Context, *ChargeReq) (*ChargeResp, error)
	// 支付和退款走队列处理
	Pay(context.Context, *PayReq) (*PayResp, error)
	Refund(context.Context, *RefundReq) (*RefundResp, error)
	// 获取集团所有充值记录
	GetTransactionsByGroup(context.Context, *GetTransactionsByGroupReq) (*GetTransactionsByGroupResp, error)
	// 根据id获取一条充值记录
	GetTransactionByID(context.Context, *GetTransactionByIDReq) (*Transaction, error)
	// 变更流水信息
	ChangeTransactionChargeMode(context.Context, *ChangeTransactionChargeModeReq) (*Transaction, error)
}

func RegisterGroupAdminServicesServer(s *grpc.Server, srv GroupAdminServicesServer) {
	s.RegisterService(&_GroupAdminServices_serviceDesc, srv)
}

func _GroupAdminServices_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/ListGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).ListGroups(ctx, req.(*ListGroupsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupAdminServices_AddGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).AddGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/AddGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).AddGroup(ctx, req.(*AddGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupAdminServices_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/UpdateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).UpdateGroup(ctx, req.(*UpdateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupAdminServices_SetGroupState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).SetGroupState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/SetGroupState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).SetGroupState(ctx, req.(*SetGroupStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupAdminServices_SetGroupRoyaltyState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupRoyaltyStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).SetGroupRoyaltyState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/SetGroupRoyaltyState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).SetGroupRoyaltyState(ctx, req.(*SetGroupRoyaltyStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupAdminServices_GetGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).GetGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/GetGroupInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).GetGroupInfo(ctx, req.(*GroupIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupAdminServices_GetGroupInfoByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupInfoByNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).GetGroupInfoByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/GetGroupInfoByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).GetGroupInfoByName(ctx, req.(*GetGroupInfoByNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupAdminServices_GetMemberInfoByCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberInfoByCustomerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).GetMemberInfoByCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/GetMemberInfoByCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).GetMemberInfoByCustomer(ctx, req.(*GetMemberInfoByCustomerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupAdminServices_Charge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).Charge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/Charge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).Charge(ctx, req.(*ChargeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupAdminServices_Pay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).Pay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/Pay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).Pay(ctx, req.(*PayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupAdminServices_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/Refund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).Refund(ctx, req.(*RefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupAdminServices_GetTransactionsByGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsByGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).GetTransactionsByGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/GetTransactionsByGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).GetTransactionsByGroup(ctx, req.(*GetTransactionsByGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupAdminServices_GetTransactionByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).GetTransactionByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/GetTransactionByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).GetTransactionByID(ctx, req.(*GetTransactionByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupAdminServices_ChangeTransactionChargeMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeTransactionChargeModeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupAdminServicesServer).ChangeTransactionChargeMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/groupadmin.GroupAdminServices/ChangeTransactionChargeMode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupAdminServicesServer).ChangeTransactionChargeMode(ctx, req.(*ChangeTransactionChargeModeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupAdminServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "groupadmin.GroupAdminServices",
	HandlerType: (*GroupAdminServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGroups",
			Handler:    _GroupAdminServices_ListGroups_Handler,
		},
		{
			MethodName: "AddGroup",
			Handler:    _GroupAdminServices_AddGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _GroupAdminServices_UpdateGroup_Handler,
		},
		{
			MethodName: "SetGroupState",
			Handler:    _GroupAdminServices_SetGroupState_Handler,
		},
		{
			MethodName: "SetGroupRoyaltyState",
			Handler:    _GroupAdminServices_SetGroupRoyaltyState_Handler,
		},
		{
			MethodName: "GetGroupInfo",
			Handler:    _GroupAdminServices_GetGroupInfo_Handler,
		},
		{
			MethodName: "GetGroupInfoByName",
			Handler:    _GroupAdminServices_GetGroupInfoByName_Handler,
		},
		{
			MethodName: "GetMemberInfoByCustomer",
			Handler:    _GroupAdminServices_GetMemberInfoByCustomer_Handler,
		},
		{
			MethodName: "Charge",
			Handler:    _GroupAdminServices_Charge_Handler,
		},
		{
			MethodName: "Pay",
			Handler:    _GroupAdminServices_Pay_Handler,
		},
		{
			MethodName: "Refund",
			Handler:    _GroupAdminServices_Refund_Handler,
		},
		{
			MethodName: "GetTransactionsByGroup",
			Handler:    _GroupAdminServices_GetTransactionsByGroup_Handler,
		},
		{
			MethodName: "GetTransactionByID",
			Handler:    _GroupAdminServices_GetTransactionByID_Handler,
		},
		{
			MethodName: "ChangeTransactionChargeMode",
			Handler:    _GroupAdminServices_ChangeTransactionChargeMode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "group-admin.proto",
}
