// Code generated by protoc-gen-go. DO NOT EDIT.
// source: verify-code.proto

package verifycode

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 发送类型
type SendType int32

const (
	SendType_SendSms  SendType = 0
	SendType_SendMail SendType = 1
)

var SendType_name = map[int32]string{
	0: "SendSms",
	1: "SendMail",
}

var SendType_value = map[string]int32{
	"SendSms":  0,
	"SendMail": 1,
}

func (x SendType) String() string {
	return proto.EnumName(SendType_name, int32(x))
}

func (SendType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a3ff5b81beb3db50, []int{0}
}

// 业务类型
type BizType int32

const (
	BizType_Login      BizType = 0
	BizType_Draw       BizType = 1
	BizType_BindCard   BizType = 2
	BizType_UnBindCard BizType = 3
	BizType_ApplyOwner BizType = 4
)

var BizType_name = map[int32]string{
	0: "Login",
	1: "Draw",
	2: "BindCard",
	3: "UnBindCard",
	4: "ApplyOwner",
}

var BizType_value = map[string]int32{
	"Login":      0,
	"Draw":       1,
	"BindCard":   2,
	"UnBindCard": 3,
	"ApplyOwner": 4,
}

func (x BizType) String() string {
	return proto.EnumName(BizType_name, int32(x))
}

func (BizType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a3ff5b81beb3db50, []int{1}
}

type CodeReq struct {
	AppID                string   `protobuf:"bytes,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	BizType              BizType  `protobuf:"varint,2,opt,name=BizType,proto3,enum=verifycode.BizType" json:"BizType,omitempty"`
	Type                 SendType `protobuf:"varint,3,opt,name=Type,proto3,enum=verifycode.SendType" json:"Type,omitempty"`
	UniqueID             string   `protobuf:"bytes,4,opt,name=UniqueID,proto3" json:"UniqueID,omitempty"`
	Mail                 *Mail    `protobuf:"bytes,5,opt,name=Mail,proto3" json:"Mail,omitempty"`
	Sms                  *Sms     `protobuf:"bytes,6,opt,name=Sms,proto3" json:"Sms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeReq) Reset()         { *m = CodeReq{} }
func (m *CodeReq) String() string { return proto.CompactTextString(m) }
func (*CodeReq) ProtoMessage()    {}
func (*CodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ff5b81beb3db50, []int{0}
}

func (m *CodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeReq.Unmarshal(m, b)
}
func (m *CodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeReq.Marshal(b, m, deterministic)
}
func (m *CodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeReq.Merge(m, src)
}
func (m *CodeReq) XXX_Size() int {
	return xxx_messageInfo_CodeReq.Size(m)
}
func (m *CodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_CodeReq proto.InternalMessageInfo

func (m *CodeReq) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *CodeReq) GetBizType() BizType {
	if m != nil {
		return m.BizType
	}
	return BizType_Login
}

func (m *CodeReq) GetType() SendType {
	if m != nil {
		return m.Type
	}
	return SendType_SendSms
}

func (m *CodeReq) GetUniqueID() string {
	if m != nil {
		return m.UniqueID
	}
	return ""
}

func (m *CodeReq) GetMail() *Mail {
	if m != nil {
		return m.Mail
	}
	return nil
}

func (m *CodeReq) GetSms() *Sms {
	if m != nil {
		return m.Sms
	}
	return nil
}

type Mail struct {
	To                   string   `protobuf:"bytes,1,opt,name=To,proto3" json:"To,omitempty"`
	FromName             string   `protobuf:"bytes,2,opt,name=FromName,proto3" json:"FromName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mail) Reset()         { *m = Mail{} }
func (m *Mail) String() string { return proto.CompactTextString(m) }
func (*Mail) ProtoMessage()    {}
func (*Mail) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ff5b81beb3db50, []int{1}
}

func (m *Mail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mail.Unmarshal(m, b)
}
func (m *Mail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mail.Marshal(b, m, deterministic)
}
func (m *Mail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mail.Merge(m, src)
}
func (m *Mail) XXX_Size() int {
	return xxx_messageInfo_Mail.Size(m)
}
func (m *Mail) XXX_DiscardUnknown() {
	xxx_messageInfo_Mail.DiscardUnknown(m)
}

var xxx_messageInfo_Mail proto.InternalMessageInfo

func (m *Mail) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Mail) GetFromName() string {
	if m != nil {
		return m.FromName
	}
	return ""
}

type Sms struct {
	Phone                string   `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	NationCode           string   `protobuf:"bytes,2,opt,name=NationCode,proto3" json:"NationCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sms) Reset()         { *m = Sms{} }
func (m *Sms) String() string { return proto.CompactTextString(m) }
func (*Sms) ProtoMessage()    {}
func (*Sms) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ff5b81beb3db50, []int{2}
}

func (m *Sms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sms.Unmarshal(m, b)
}
func (m *Sms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sms.Marshal(b, m, deterministic)
}
func (m *Sms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sms.Merge(m, src)
}
func (m *Sms) XXX_Size() int {
	return xxx_messageInfo_Sms.Size(m)
}
func (m *Sms) XXX_DiscardUnknown() {
	xxx_messageInfo_Sms.DiscardUnknown(m)
}

var xxx_messageInfo_Sms proto.InternalMessageInfo

func (m *Sms) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Sms) GetNationCode() string {
	if m != nil {
		return m.NationCode
	}
	return ""
}

type CodeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeResp) Reset()         { *m = CodeResp{} }
func (m *CodeResp) String() string { return proto.CompactTextString(m) }
func (*CodeResp) ProtoMessage()    {}
func (*CodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ff5b81beb3db50, []int{3}
}

func (m *CodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeResp.Unmarshal(m, b)
}
func (m *CodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeResp.Marshal(b, m, deterministic)
}
func (m *CodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeResp.Merge(m, src)
}
func (m *CodeResp) XXX_Size() int {
	return xxx_messageInfo_CodeResp.Size(m)
}
func (m *CodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_CodeResp proto.InternalMessageInfo

type VerifyReq struct {
	AppID                string   `protobuf:"bytes,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	BizType              int32    `protobuf:"varint,2,opt,name=BizType,proto3" json:"BizType,omitempty"`
	Type                 SendType `protobuf:"varint,3,opt,name=Type,proto3,enum=verifycode.SendType" json:"Type,omitempty"`
	UniqueID             string   `protobuf:"bytes,4,opt,name=UniqueID,proto3" json:"UniqueID,omitempty"`
	Code                 string   `protobuf:"bytes,5,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyReq) Reset()         { *m = VerifyReq{} }
func (m *VerifyReq) String() string { return proto.CompactTextString(m) }
func (*VerifyReq) ProtoMessage()    {}
func (*VerifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ff5b81beb3db50, []int{4}
}

func (m *VerifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReq.Unmarshal(m, b)
}
func (m *VerifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReq.Marshal(b, m, deterministic)
}
func (m *VerifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReq.Merge(m, src)
}
func (m *VerifyReq) XXX_Size() int {
	return xxx_messageInfo_VerifyReq.Size(m)
}
func (m *VerifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReq proto.InternalMessageInfo

func (m *VerifyReq) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *VerifyReq) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *VerifyReq) GetType() SendType {
	if m != nil {
		return m.Type
	}
	return SendType_SendSms
}

func (m *VerifyReq) GetUniqueID() string {
	if m != nil {
		return m.UniqueID
	}
	return ""
}

func (m *VerifyReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type VerifyResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResp) Reset()         { *m = VerifyResp{} }
func (m *VerifyResp) String() string { return proto.CompactTextString(m) }
func (*VerifyResp) ProtoMessage()    {}
func (*VerifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ff5b81beb3db50, []int{5}
}

func (m *VerifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResp.Unmarshal(m, b)
}
func (m *VerifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResp.Marshal(b, m, deterministic)
}
func (m *VerifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResp.Merge(m, src)
}
func (m *VerifyResp) XXX_Size() int {
	return xxx_messageInfo_VerifyResp.Size(m)
}
func (m *VerifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResp proto.InternalMessageInfo

func (m *VerifyResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *VerifyResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("verifycode.SendType", SendType_name, SendType_value)
	proto.RegisterEnum("verifycode.BizType", BizType_name, BizType_value)
	proto.RegisterType((*CodeReq)(nil), "verifycode.CodeReq")
	proto.RegisterType((*Mail)(nil), "verifycode.Mail")
	proto.RegisterType((*Sms)(nil), "verifycode.Sms")
	proto.RegisterType((*CodeResp)(nil), "verifycode.CodeResp")
	proto.RegisterType((*VerifyReq)(nil), "verifycode.VerifyReq")
	proto.RegisterType((*VerifyResp)(nil), "verifycode.VerifyResp")
}

func init() { proto.RegisterFile("verify-code.proto", fileDescriptor_a3ff5b81beb3db50) }

var fileDescriptor_a3ff5b81beb3db50 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xed, 0xc6, 0x76, 0x3e, 0xa6, 0x28, 0xb8, 0x43, 0x40, 0x56, 0x0e, 0x28, 0x58, 0x20, 0x45,
	0x95, 0xe2, 0x08, 0x83, 0x04, 0x12, 0xa7, 0xa6, 0x11, 0xa2, 0x52, 0x5b, 0x90, 0x93, 0x72, 0xe0,
	0xe6, 0xc4, 0x8b, 0x59, 0xc9, 0xde, 0xdd, 0x7a, 0x4d, 0xab, 0x70, 0xe1, 0x57, 0xf0, 0xf3, 0xf8,
	0x2f, 0x68, 0xd7, 0x8e, 0x9b, 0x08, 0xb8, 0xf5, 0x36, 0xf3, 0xde, 0xf3, 0xbc, 0x99, 0x97, 0x0d,
	0x1c, 0xdd, 0xd0, 0x82, 0x7d, 0xdd, 0x4c, 0xd6, 0x22, 0xa1, 0x81, 0x2c, 0x44, 0x29, 0x10, 0x2a,
	0x48, 0x23, 0xfe, 0x6f, 0x02, 0x9d, 0x53, 0x91, 0xd0, 0x88, 0x5e, 0xe3, 0x00, 0x9c, 0x13, 0x29,
	0xcf, 0xe6, 0x1e, 0x19, 0x91, 0x71, 0x2f, 0xaa, 0x1a, 0x9c, 0x40, 0x67, 0xc6, 0x7e, 0x2c, 0x37,
	0x92, 0x7a, 0xad, 0x11, 0x19, 0xf7, 0xc3, 0x47, 0xc1, 0xdd, 0xf7, 0x41, 0x4d, 0x45, 0x5b, 0x0d,
	0x8e, 0xc1, 0x36, 0x5a, 0xcb, 0x68, 0x07, 0xbb, 0xda, 0x05, 0xe5, 0x89, 0x11, 0x1b, 0x05, 0x0e,
	0xa1, 0x7b, 0xc5, 0xd9, 0xf5, 0x77, 0x7a, 0x36, 0xf7, 0x6c, 0xe3, 0xd8, 0xf4, 0xf8, 0x1c, 0xec,
	0x8b, 0x98, 0x65, 0x9e, 0x33, 0x22, 0xe3, 0xc3, 0xd0, 0xdd, 0x9d, 0xa2, 0xf1, 0xc8, 0xb0, 0xf8,
	0x0c, 0xac, 0x45, 0xae, 0xbc, 0xb6, 0x11, 0x3d, 0xdc, 0xb3, 0xca, 0x55, 0xa4, 0x39, 0x3f, 0xac,
	0x06, 0x61, 0x1f, 0x5a, 0x4b, 0x51, 0x1f, 0xd6, 0x5a, 0x0a, 0x6d, 0xfe, 0xbe, 0x10, 0xf9, 0x65,
	0x9c, 0x57, 0x67, 0xf5, 0xa2, 0xa6, 0xf7, 0xdf, 0x99, 0xb1, 0x3a, 0x8e, 0x4f, 0xdf, 0x04, 0xa7,
	0xdb, 0x38, 0x4c, 0x83, 0x4f, 0x01, 0x2e, 0xe3, 0x92, 0x09, 0xae, 0x53, 0xab, 0x3f, 0xdd, 0x41,
	0x7c, 0x80, 0x6e, 0x95, 0xa7, 0x92, 0xfe, 0x2f, 0x02, 0xbd, 0xcf, 0x66, 0xa9, 0xff, 0xc7, 0xeb,
	0xed, 0xc7, 0xeb, 0xdc, 0x77, 0x92, 0x08, 0xb6, 0xd9, 0xd4, 0x31, 0xb8, 0xa9, 0xfd, 0x10, 0x60,
	0xbb, 0x96, 0x92, 0x8d, 0x82, 0x18, 0x7b, 0x53, 0xa3, 0x0b, 0xd6, 0x85, 0x4a, 0xeb, 0xf3, 0x74,
	0x79, 0xfc, 0x02, 0xba, 0x5b, 0x57, 0x3c, 0x84, 0x8e, 0xae, 0x17, 0xb9, 0x72, 0x0f, 0xf0, 0x41,
	0x45, 0xe8, 0x94, 0x5d, 0x72, 0x7c, 0xde, 0x9c, 0x83, 0x3d, 0x70, 0xce, 0x45, 0xca, 0xb8, 0x7b,
	0x80, 0x5d, 0xb0, 0xe7, 0x45, 0x7c, 0xeb, 0x12, 0xad, 0x9e, 0x31, 0x9e, 0x9c, 0xc6, 0x45, 0xe2,
	0xb6, 0xb0, 0x0f, 0x70, 0xc5, 0x9b, 0xde, 0xd2, 0xfd, 0x89, 0x94, 0xd9, 0xe6, 0xe3, 0x2d, 0xa7,
	0x85, 0x6b, 0x87, 0x3f, 0xe1, 0xa8, 0x5a, 0x54, 0x2f, 0xb5, 0xa0, 0xc5, 0x0d, 0x5b, 0x53, 0x7c,
	0x09, 0xb6, 0x36, 0xc4, 0xbd, 0x77, 0x58, 0xbf, 0xe1, 0xe1, 0xe0, 0x6f, 0x50, 0x49, 0x7c, 0x03,
	0xed, 0x6a, 0x0e, 0x3e, 0xde, 0xe5, 0x9b, 0xdf, 0x66, 0xf8, 0xe4, 0x5f, 0xb0, 0x92, 0xb3, 0xb7,
	0x1f, 0xac, 0x2f, 0xaf, 0x53, 0x56, 0x66, 0xf1, 0x2a, 0x48, 0x05, 0x13, 0x65, 0xc0, 0x69, 0x39,
	0x55, 0x09, 0x9d, 0xac, 0x62, 0x45, 0xa7, 0xe6, 0xff, 0xb4, 0x16, 0xd9, 0x34, 0x15, 0x59, 0xcc,
	0xd3, 0xe9, 0xdd, 0x90, 0x55, 0xdb, 0x70, 0xaf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x11, 0x49,
	0x84, 0x5d, 0x80, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VerifyCodeServiceClient is the client API for VerifyCodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VerifyCodeServiceClient interface {
	// 发送验证码
	Send(ctx context.Context, in *CodeReq, opts ...grpc.CallOption) (*CodeResp, error)
	// 检查验证码
	Verify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyResp, error)
}

type verifyCodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewVerifyCodeServiceClient(cc *grpc.ClientConn) VerifyCodeServiceClient {
	return &verifyCodeServiceClient{cc}
}

func (c *verifyCodeServiceClient) Send(ctx context.Context, in *CodeReq, opts ...grpc.CallOption) (*CodeResp, error) {
	out := new(CodeResp)
	err := c.cc.Invoke(ctx, "/verifycode.VerifyCodeService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifyCodeServiceClient) Verify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyResp, error) {
	out := new(VerifyResp)
	err := c.cc.Invoke(ctx, "/verifycode.VerifyCodeService/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifyCodeServiceServer is the server API for VerifyCodeService service.
type VerifyCodeServiceServer interface {
	// 发送验证码
	Send(context.Context, *CodeReq) (*CodeResp, error)
	// 检查验证码
	Verify(context.Context, *VerifyReq) (*VerifyResp, error)
}

func RegisterVerifyCodeServiceServer(s *grpc.Server, srv VerifyCodeServiceServer) {
	s.RegisterService(&_VerifyCodeService_serviceDesc, srv)
}

func _VerifyCodeService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyCodeServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifycode.VerifyCodeService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyCodeServiceServer).Send(ctx, req.(*CodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifyCodeService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyCodeServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifycode.VerifyCodeService/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyCodeServiceServer).Verify(ctx, req.(*VerifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _VerifyCodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "verifycode.VerifyCodeService",
	HandlerType: (*VerifyCodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _VerifyCodeService_Send_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _VerifyCodeService_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verify-code.proto",
}
